#!/bin/bash
#  Copyright (C) 2010-2012  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=2.4.13
ARCH=${ARCH:-i486}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -march=i486 -mtune=i686}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j5}

PKG=${TMP}/package-libgphoto2

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/libgphoto2-${V}
lzip -cd ${CWD}/libgphoto2-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/libgphoto2-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

CFLAGS="$DCFLAGS" \
CXXFLAGS="$DCFLAGS" \
udevscriptdir=/lib/udev \
./configure \
 --prefix=/usr \
 --mandir=/usr/man \
 --docdir=/usr/doc/libgphoto2-${V} \
 --with-doc-dir=/usr/doc/libgphoto2-${V} \
 --with-html-dir=/usr/doc/libgphoto2-${V}/html \
 --localstatedir=/var \
 --disable-static \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS udevscriptdir=/lib/udev utilsdir=/usr/bin
make install DESTDIR=$PKG

# Remove circular symlink:
rm -f ${PKG}/usr/include/gphoto2/gphoto2

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

# Make UDEV and HAL rules:
mkdir -p ${PKG}/lib/udev/rules.d
mkdir -p ${PKG}/usr/share/hal/fdi/information/20thirdparty
( cd ${PKG}/usr/lib/libgphoto2

  export LIBDIR=${PKG}/usr/lib
  export LD_LIBRARY_PATH=${PKG}/usr/lib
  export CAMLIBS=${PKG}/usr/lib/libgphoto2/${V}

  ./print-camera-list udev-rules version 136 \
   > ${PKG}/lib/udev/rules.d/40-libgphoto2.rules

  ./print-camera-list hal-fdi | grep -v "<!-- This file was generated" \
   > ${PKG}/usr/share/hal/fdi/information/20thirdparty/10-camera-libgphoto2.fdi
)

# Compress and link manpages:
( cd $PKG/usr/man
  find . -type f -exec gzip -9N '{}' +
  find . -type l | while read file ; do
    ln -sf $(readlink $file).gz ${file}.gz
    rm $file
  done
)

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/libgphoto2-${V}-${ARCH}-${B}.tlz

