#!/bin/bash
#  Copyright (C) 2010-2012  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=2.24.10
ARCH=${ARCH:-x86_64}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -mtune=generic}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j5}

PKG=${TMP}/package-gtk2+-2

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/gtk+-${V}
tar -xvf ${CWD}/gtk+-${V}.tar.lz -C $TMP

cd ${TMP}/gtk+-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

# Apply patches from OpenBSD.

zcat ${CWD}/patches/patch-configure.gz | patch -p0 --verbose

# https://bugzilla.gnome.org/show_bug.cgi?id=629878
zcat ${CWD}/patches/patch-gtk_Makefile_in.gz | patch -p0 --verbose

zcat ${CWD}/patches/patch-gtk_gtkprintunixdialog_c.gz | patch -p0 --verbose
zcat ${CWD}/patches/patch-gtk_gtksettings_c.gz | patch -p0 --verbose

# Custom patch:
zcat ${CWD}/patches/gdkxid.nowarningflood.diff.gz | patch -p1 --verbose

CFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --libdir=/usr/lib64 \
 --sysconfdir=/etc \
 --mandir=/usr/man \
 --infodir=/usr/info \
 --localstatedir=/var \
 --disable-static \
 --disable-papi \
 --disable-introspection \
 --disable-silent-rules \
 --disable-gtk-doc \
 --enable-man=no \
 --with-xinput=yes \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS
make install DESTDIR=$PKG

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

# Handle config:
mv ${PKG}/etc/gtk-2.0/im-multipress.conf{,.new}

# Add the documentation:
mkdir -p ${PKG}/usr/doc/gtk2+-${V}
cp -a \
 AUTHORS COPYING ChangeLog ChangeLog.gtk-printing HACKING \
 README README.commits \
 ${PKG}/usr/doc/gtk2+-${V}

# Add the post install script:
mkdir -p ${PKG}/install
cat << "EOF" > ${PKG}/install/post-install
# Handle config files:
config() {
  local new old
  new="$1"
  old=${1%.new}
  if [ ! -r $old ]; then
    mv $new $old
  elif [ "$(md5sum $old | cut -f 1 -d ' ')" = "$(md5sum $new | cut -f 1 -d ' ')" ]; then
    rm $new
  else
    echo "You have a new config file \"${ROOT}/${new}\" at your consideration."
  fi
}

config etc/gtk-2.0/im-multipress.conf.new

# Update gtk-2.0 modules:
if [ -x /usr/bin/gtk-query-immodules-2.0 ]; then
  /usr/bin/gtk-query-immodules-2.0 > /etc/gtk-2.0/gtk.immodules
fi
# Update gdk pixbuffer loaders:
if [ -x /usr/bin/gdk-pixbuf-query-loaders ]; then
  /usr/bin/gdk-pixbuf-query-loaders > /etc/gtk-2.0/gdk-pixbuf.loaders
fi

EOF

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/descriptions/gtk/?? ${PKG}/description

cd $PKG
makepkg -l prepend ${OUT}/gtk2+-${V}-${ARCH}-${B}.tlz

