#!/bin/bash
#  Copyright (C) 2009-2012  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=2.19.1
ARCH=${ARCH:-i486}
B=3

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -march=i486 -mtune=i686}

PKG=${TMP}/package-util-linux

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/util-linux-${V}
lzip -cd ${CWD}/util-linux-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/util-linux-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

# Patch the question to save/write in `cfdisk',
# since the default question is too long:
zcat ${CWD}/cfdisk_question.diff.gz | patch -p1 --verbose

zcat ${CWD}/util-linux.git-696b84b30a31dcb2fb1383d5afe08abcc1597eab.patch.gz | \
 patch -p1 --verbose

CFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --infodir=/usr/info \
 --mandir=/usr/man \
 --enable-arch \
 --enable-mesg \
 --enable-raw \
 --enable-reset \
 --enable-wall \
 --enable-write \
 --enable-partx \
 --enable-use-tty-group \
 --enable-libuuid \
 --enable-libblkid \
 --enable-libmount \
 --disable-kill \
 --disable-last \
 --disable-login-utils \
 --disable-uuidd \
 --build=${ARCH}-dragora-linux-gnu

make V=1
make install DESTDIR=$PKG

# Increments a little the security:
for file in ${PKG}/sbin/* ${PKG}/usr/sbin/* ; do
  [[ -x $file && ! -L $file ]] && chmod -v 750 $file
done

# Strip ELF's:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

# Make symlink compatibility:
( cd ${PKG}/sbin
  ln -sf hwclock clock
  chmod 755 hwclock  ## Set perm for the user.
)

# Compress GNU info documents (if needed):
if [[ -d ${PKG}/usr/info ]]; then
  ( cd ${PKG}/usr/info
    rm -f dir
    gzip -9N *
  )
fi

# Compress man-pages:
gzip -9N ${PKG}/usr/man/man?/*.?
( cd ${PKG}/usr/man/man8 ; ln -sf hwclock.8.gz clock.8.gz )

# Add documentation:
mkdir -p ${PKG}/usr/doc/util-linux-${V}
cp -a \
 ABOUT-NLS AUTHORS COPYING DEPRECATED NEWS README* TODO \
 ${PKG}/usr/doc/util-linux-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/?? ${PKG}/description

cd $PKG
makepkg -l ${OUT}/util-linux-${V}-${ARCH}-${B}.tlz

