#!/bin/bash
#  Copyright (C) 2011  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

P=mesa-demos
V=${V:-8.0.1}
ARCH=${ARCH:-x86_64}
B=${B:-2}

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -mtune=generic}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j7}

PKG=${TMP}/package-${P}

rm -rf $PKG
mkdir -p $PKG $OUT

cd $TMP
rm -rf ${P}-${V}

rm -rf ${TMP}/${P}-${V}-libre
echo "Uncompressing the tarball..."
tar -xvf ${CWD}/${P}-${V}-libre.tar.lz -C $TMP

cd ${TMP}/${P}-${V}-libre

# Don't build pointblast and spriteblast. This programs are non-free.
#
# http://bugs.gnewsense.org/Bugs/00353
#
( cd src/demos
  zcat ${CWD}/no-pointblast-spriteblast.diff.gz | patch -p0 --verbose
)

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \
 \) -exec chmod 755 {} + \
 -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \
 \) -exec chmod 644 {} +

CFLAGS="$DCFLAGS" \
CXXFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --libdir=/usr/lib64 \
 --infodir=/usr/info \
 --mandir=/usr/man \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS || make;
make install DESTDIR=$PKG

# Rename programs provided in other packages:
for file in bitmap clear line ; do
  if [[ -r ${PKG}/usr/bin/$file ]]; then
    ( cd ${PKG}/usr/bin
      mv $file{,-mesa-demos}
    )
  fi
done

# Compress .info page(s)?:
if [[ -d ${PKG}/usr/info ]]; then
  ( cd ${PKG}/usr/info
    rm -f dir  # Redundancy.
    gzip -9N *.info*
  )
fi

# Compress and link .man page(s)?:
if [[ -d ${PKG}/usr/man ]]; then
  ( cd ${PKG}/usr/man
    find . -type f -exec gzip -9N '{}' +
    find . -type l | while read file ; do
      ln -sf $(readlink $file).gz ${file}.gz
      rm $file
    done
  )
fi

cd $PKG

# Strip binaries & libraries:
find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
 cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || :

# Copy description files, adding the post install script:
mkdir -p description
install -m 644 ${CWD}/descriptions/demos/?? description/

# Build the package:
makepkg -l ${OUT}/${P}-${V}-${ARCH}-${B}.tlz

