#!/bin/bash
#  Copyright (C) 2010, 2012  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=7.4
ARCH=${ARCH:-x86_64}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -mtune=generic}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j1}

PKG=${TMP}/package-gdb

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/gdb-${V}
tar -xvf ${CWD}/gdb-${V}.tar.lz -C $TMP

cd ${TMP}/gdb-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

CFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --libdir=/usr/lib64 \
 --infodir=/usr/info \
 --mandir=/usr/man \
 --with-system-readline \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS
make install DESTDIR=$PKG

# Files provided by binutils package:
rm -f \
 ${PKG}/usr/lib64/libbfd.la \
 ${PKG}/usr/lib64/libopcodes.a \
 ${PKG}/usr/lib64/libopcodes.la \
 ${PKG}/usr/lib64/libiberty.a \
 ${PKG}/usr/lib64/libbfd.a
rm -f \
 ${PKG}/usr/include/symcat.h \
 ${PKG}/usr/include/bfdlink.h \
 ${PKG}/usr/include/bfd.h \
 ${PKG}/usr/include/dis-asm.h \
 ${PKG}/usr/include/ansidecl.h

rmdir ${PKG}/usr/lib64 ${PKG}/usr/include || true;

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

# Compress manpages and info pages:
gzip -9N ${PKG}/usr/man/man?/*.?  # Compress manpages.

# More files provided by binutils package:
rm -f \
 ${PKG}/usr/info/configure.info \
 ${PKG}/usr/info/bfd.info \
 ${PKG}/usr/info/standards.info

rm -f ${PKG}/usr/info/dir         # Redundancy.
gzip -9N ${PKG}/usr/info/*        # GNU pages.

# Add the documentation:
mkdir -p ${PKG}/usr/doc/gdb-${V}
cp -a \
 COPYING* ChangeLog README* \
 ${PKG}/usr/doc/gdb-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/?? ${PKG}/description

cd $PKG
makepkg -l ${OUT}/gdb-${V}-${ARCH}-${B}.tlz

