#!/bin/bash
#  Copyright (C) 2010, 2012  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=1.900.1
ARCH=${ARCH:-x86_64}
B=3

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -mtune=generic}

PKG=${TMP}/package-jasper

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/jasper-${V}
lzip -cd ${CWD}/jasper-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/jasper-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

# Apply security fixes from BLFS:
zcat ${CWD}/jasper-1.900.1-security_fixes-1.patch.gz | patch -p1 --verbose

# Apply a dose of fixes from Debian:
zcat ${CWD}/patches/01-misc-fixes.patch.gz | \
 patch -p1 --verbose
zcat ${CWD}/patches/02-fix-filename-buffer-overflow.patch.gz | \
 patch -p1 --verbose
zcat ${CWD}/patches/03-CVE-2011-4516-and-CVE-2011-4517.patch.gz | \
 patch -p1 --verbose

CFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --localstatedir=/var \
 --enable-shared \
 --libdir=/usr/lib64 \
 --disable-static \
 --build=${ARCH}-dragora-linux-gnu

make
make install DESTDIR=$PKG

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

if [[ -d ${PKG}/usr/man ]]; then  # Compress manpages.
  gzip -9N ${PKG}/usr/man/man?/*.?
fi

# Add the documentation:
mkdir -p ${PKG}/usr/doc/jasper-${V}
cp -a \
 COPYRIGHT ChangeLog LICENSE NEWS README \
 ${PKG}/usr/doc/jasper-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/?? ${PKG}/description

cd $PKG
makepkg -l ${OUT}/jasper-${V}-${ARCH}-${B}.tlz

