#!/bin/bash
#  Copyright (C) 2010-2011  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=3.0.6
ARCH=${ARCH:-i486}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -march=i486 -mtune=i686}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j4}

PKG=${TMP}/package-xfsdump

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/xfsdump-${V}
lzip -cd ${CWD}/xfsdump-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/xfsdump-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

export OPTIMIZER="$DCFLAGS" DEBUG=-DNDEBUG

./configure \
 --prefix=/usr \
 --sbindir=/sbin \
 --mandir=/usr/man \
 --docdir=/usr/doc/xfsdump-${V} \
 --enable-shared \
 --enable-gettext \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS
make install DIST_ROOT=$PKG

# Clobber the existing broken symlink of xfsdump:
rm -f ${PKG}/sbin/xfsdump
cp -a dump/xfsdump ${PKG}/sbin
( cd ${PKG}/sbin
  ln -sf xfsdump xfsrestore
)

# Increments a little "the security":
find ${PKG}/sbin -type f -exec chmod -v 0750 '{}' \;

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

# The documentation is already installed,
# but the timestamp is not the same:
rm -rf ${PKG}/usr/share/doc
mkdir -p ${PKG}/usr/doc/xfsdump-${V}
( cd doc
  cp -a \
   CHANGES.gz COPYING ../README \
   ${PKG}/usr/doc/xfsdump-${V}
)
rmdir ${PKG}/usr/share || true;

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description-xfsdump/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/xfsdump-${V}-${ARCH}-${B}.tlz

