#!/bin/bash
#  Copyright (C) 2010-2012  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=3.1.8
ARCH=${ARCH:-i486}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -march=i486 -mtune=i686}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j4}

PKG=${TMP}/package-xfsprogs

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/xfsprogs-${V}
lzip -cd ${CWD}/xfsprogs-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/xfsprogs-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

export OPTIMIZER="$DCFLAGS" DEBUG=-DNDEBUG

./configure \
 --prefix=/usr \
 --sbindir=/sbin \
 --bindir=/usr/sbin \
 --libdir=/lib \
 --libexecdir=/usr/lib \
 --includedir=/usr/include \
 --mandir=/usr/man \
 --datadir=/usr/share \
 --docdir=/usr/doc/xfsprogs-${V} \
 --enable-shared \
 --enable-gettext \
 --enable-readline \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS
make install DIST_ROOT=$PKG
make install-dev DIST_ROOT=$PKG

# Increments a little "the security":
find ${PKG}/sbin -type f -exec chmod -v 0750 '{}' \;

# Remove bogus files:
find ${PKG}/lib \( -name '*.a' -o -name '*.la' -o -name '*.so' \) -delete

# Set properly permissions:
chmod 755 ${PKG}/lib/*.so*

# Regenerate the symlink for "libhandle.so":
mkdir -p ${PKG}/usr/lib
( cd ${PKG}/usr/lib ; ln -sf ../../lib/libhandle.so.1 libhandle.so )

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
  find . -type f | xargs file | awk '/current ar archive/' | \
   cut -f 1 -d : | xargs strip --strip-debug 2> /dev/null || :
)

# The documentation is already installed,
# but the timestamp is not the same:
rm -rf ${PKG}/usr/share/doc
mkdir -p ${PKG}/usr/doc/xfsprogs-${V}
( cd doc
  cp -a \
   CHANGES.gz COPYING CREDITS ../README \
   ${PKG}/usr/doc/xfsprogs-${V}
)

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description-xfsprogs/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/xfsprogs-${V}-${ARCH}-${B}.tlz

