#!/bin/bash
#  Copyright (C) 2010-2011  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=1.8.2
JV=4.8.2  # JUnit version.
ARCH=${ARCH:-x86_64}
B=1

PKG=${TMP}/package-apache-ant

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/apache-ant-${V}
lzip -cd ${CWD}/apache-ant-${V}-src.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/apache-ant-${V}

# JUnit is required:
unzip ${CWD}/junit${JV}.zip

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

# Don't perform the tests:
sed -i 's;jars,test-jar;jars;' build.xml

# Build and install ant:
mkdir -p ${PKG}/usr/share/java/apache-ant
sh build.sh -Ddist.dir=${PKG}/usr/share/java/apache-ant dist

# Purge package:
find $PKG -type f \( -name '*.bat' -o -name '*.cmd' \) -delete

# Install JUnit:
install -m 644 junit${JV}/junit-${JV}.jar \
 -D ${PKG}/usr/share/java/junit.jar
( cd ${PKG}/usr/share/java/apache-ant/lib
  ln -sf ../../junit.jar .
)

# Add the profile:
mkdir -p ${PKG}/etc/profile.d
zcat ${CWD}/profile.d/apache-ant.gz \
 > ${PKG}/etc/profile.d/apache-ant.new
chmod 755 ${PKG}/etc/profile.d/apache-ant.new

# Add the documentation:
mkdir -p ${PKG}/usr/doc/apache-ant-${V}
cp -a \
 KEYS LICENSE NOTICE README WHATSNEW \
 ${PKG}/usr/doc/apache-ant-${V}

# Add the post-install script:
mkdir -p ${PKG}/install
zcat ${CWD}/post-install.gz > ${PKG}/install/post-install

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/apache-ant-${V}-${ARCH}-${B}.tlz

