#!/bin/bash
#  Copyright (C) 2010  Matías A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=0.15.1b
ARCH=${ARCH:-x86_64}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -fPIC}

PKG=${TMP}/package-libid3tag

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/libid3tag-${V}
lzip -cd ${CWD}/libid3tag-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/libid3tag-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

# Fix for CVE-2008-2109 (#445812):
zcat ${CWD}/patches/libid3tag-0.15.1b-fix_overflow.patch.gz | patch -p0 --verbose

CFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --libdir=/usr/lib64 \
 --enable-shared \
 --disable-static \
 --disable-debugging \
 --build=${ARCH}-dragora-linux-gnu

make
make install DESTDIR=$PKG

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

# Write the .pc for pkgconfig:
mkdir -p ${PKG}/usr/lib64/pkgconfig
cat << EOF > ${PKG}/usr/lib64/pkgconfig/id3tag.pc
prefix=/usr
exec_prefix=\${prefix}
libdir=\${exec_prefix}/lib64
includedir=\${prefix}/include

Name: id3tag
Description: ID3 tag manipulation library
Version: ${V}
Requires:
Libs: -L\${libdir} -lid3tag -lz
Cflags: -I\${includedir}

EOF

# Add the documentation:
mkdir -p ${PKG}/usr/doc/libid3tag-${V}
cp -a \
 CHANGES COPYING COPYRIGHT CREDITS README TODO VERSION \
 ${PKG}/usr/doc/libid3tag-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/libid3tag-${V}-${ARCH}-${B}.tlz

