#!/bin/bash
#  Copyright (C) 2010-2012  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=1.2.1
ARCH=${ARCH:-x86_64}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:= -mtune=generic}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j3}

PKG=${TMP}/package-libpcap

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/libpcap-${V}
tar xvf ${CWD}/libpcap-${V}.tar.lz -C $TMP

cd ${TMP}/libpcap-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

#zcat ${CWD}/patches/libpcap-soname.patch.gz | patch -p1 --verbose

CFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --localstatedir=/var \
 --libdir=/usr/lib64 \
 --mandir=/usr/man \
 --enable-ipv6 \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS || return 1
mkdir -p ${PKG}/usr/bin
make install DESTDIR=$PKG
make install-shared DESTDIR=$PKG

# Make symlinks:
( cd ${PKG}/usr/lib64
  ln -sf libpcap.so.${V} libpcap.so
  ln -sf libpcap.so.${V} libpcap.so.1
)

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
  find . -type f | xargs file | awk '/current ar archive/' | \
   cut -f 1 -d : | xargs strip --strip-debug 2> /dev/null
)

# Compress and link manpages:
( cd ${PKG}/usr/man
  find . -type f -exec gzip -9Nf '{}' +
  find . -type l | while read file ; do
    ln -sf $(readlink $file).gz ${file}.gz
    rm $file
  done
)

# Add the documentation:
mkdir -p ${PKG}/usr/doc/libpcap-${V}
cp -a \
 CHANGES CREDITS LICENSE README README.linux TODO VERSION \
 ${PKG}/usr/doc/libpcap-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/libpcap-${V}-${ARCH}-${B}.tlz

