#!/bin/bash
#  Copyright (C) 2010  Matías A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=0.6.20
LIBEXIF_GTK_V=0.3.5
ARCH=${ARCH:-x86_64}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -mtune=generic}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j4}

PKG=${TMP}/package-libexif

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/libexif-${V}
lzip -cd ${CWD}/libexif-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/libexif-${V}

lzip -cd ${CWD}/libexif-gtk-${LIBEXIF_GTK_V}.tar.lz | tar -xvf -

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

export CFLAGS="$DCFLAGS"

pushd libexif-gtk-${LIBEXIF_GTK_V}
  zcat ${CWD}/patches/libexif-no_deprecated.patch.gz | patch -p1 --verbose
  zcat ${CWD}/patches/gtk-options.patch.gz | patch -p1 --verbose
  sed -i "s@exif-mem.h@libexif/&@g" configure
  ./configure \
   --prefix=/usr \
   --libdir=/usr/lib64 \
   --localstatedir=/var \
   --disable-static \
   --build=${ARCH}-dragora-linux-gnu
  make
  make install DESTDIR=$PKG
  mkdir -p ${PKG}/usr/doc/libexif-${V}/libexif-gtk-${LIBEXIF_GTK_V}
  cp -a \
   ABOUT-NLS AUTHORS COPYING ChangeLog NEWS README \
   ${PKG}/usr/doc/libexif-${V}/libexif-gtk-${LIBEXIF_GTK_V}
popd

./configure \
 --prefix=/usr \
 --libdir=/usr/lib64 \
 --with-doc-dir=/usr/doc/libexif-${V} \
 --disable-static \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS
make install DESTDIR=$PKG

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

# Re-copy the documentation maintaning the timestamp:
rm -rf ${PKG}/usr/share/doc
mkdir -p ${PKG}/usr/doc/libexif-${V}
cp -a \
 ABOUT-NLS AUTHORS COPYING ChangeLog NEWS README \
 ${PKG}/usr/doc/libexif-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/libexif-${V}-${ARCH}-${B}.tlz

