#! /bin/sh
#  Copyright (C) 2012, 2013, 2014  Matias A. Fonzo
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Autodetermine the path of /tools
if [ ! -L /tools ]; then
  echo "Cannot determine \$ROOT. The symlink \"/tools\" doesn't exists."
  exit 1
fi
if [ -L /tools ] && [ ! -e /tools ]; then
  echo "/tools is a dangling symlink."
  exit 1
fi
# Reads the link of /tools without including the last string "/tools"
ROOT=$(readlink /tools | sed -e 's/\/tools//')

# Functions
_umount() {
  NODE="$1"
  if mount | grep -q "$NODE" ; then
    echo "Unmounting $NODE ..."
    umount $NODE
    if [ $? -ne 0 ]; then
      echo "Forcing ..."
      umount -f $NODE
    fi
  fi
}

echo "Mounting directories ..."
mount -o bind "$(pwd)/archive" ${ROOT}/usr/src/dragora/archive
mount -o bind "$(pwd)/patches" ${ROOT}/usr/src/dragora/patches
mount -o bind "$(pwd)/recipes" ${ROOT}/usr/src/dragora/recipes
mount -o bind "$(pwd)/sources" ${ROOT}/usr/src/dragora/sources

echo "Mounting virtual file systems ..."
mount -o bind /dev ${ROOT}/dev
mount -t devpts devpts ${ROOT}/dev/pts
mount -t tmpfs shm ${ROOT}/dev/shm
mount -t proc proc ${ROOT}/proc
mount -t sysfs sysfs ${ROOT}/sys

echo "Entering chroot (${ROOT}) ..."
chroot $ROOT /tools/bin/env -i \
 PATH=/bin:/usr/bin:/sbin:/usr/sbin:/tools/bin:/tools/sbin \
 SHELL=/bin/sh \
 TERM="$TERM" \
 PS1='\u:\w\$ ' \
 HOME=/root \
 /bin/sh --login

_umount ${ROOT}/usr/src/dragora/archive
_umount ${ROOT}/usr/src/dragora/patches
_umount ${ROOT}/usr/src/dragora/recipes
_umount ${ROOT}/usr/src/dragora/sources
_umount ${ROOT}/sys
_umount ${ROOT}/proc
_umount ${ROOT}/dev/shm
_umount ${ROOT}/dev/pts
_umount ${ROOT}/dev

echo;  ## A new line for the prompt

