#!/bin/bash
#  Copyright (C) 2010  Matías A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=20100419git
ARCH=${ARCH:-x86_64}
B=1

PKG=${TMP}/package-b43-asm

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/b43-tools
lzip -cd ${CWD}/b43-tools-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/b43-tools

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

cd assembler
make
install -m 755 b43-asm     -D ${PKG}/usr/bin/b43-asm
install -m 755 b43-asm.bin -D ${PKG}/usr/bin/b43-asm.bin
strip --strip-unneeded        ${PKG}/usr/bin/b43-asm.bin

mkdir -p ${PKG}/usr/doc/b43-asm-${V}
cp -a COPYING README ${PKG}/usr/doc/b43-asm-${V}  # Copy documentation.

mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description  # Copy description files.

cd $PKG
makepkg -l ${OUT}/b43-asm-${V}-${ARCH}-${B}.tlz

