#!/bin/bash
#  Copyright (C) 2009-2011  Matías A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources-binutils}-$(mcookie)
OUT=${OUT:-/tmp/packages}

V=2.22
ARCH=${ARCH:-i486}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -march=i486 -mtune=i686}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j4}

# System type:
TYPE=${ARCH}-dragora-linux-gnu

PKG=${TMP}/package-binutils

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/binutils-${V}
lzip -cd ${CWD}/binutils-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/binutils-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

# Removes the outdated standards.info file:
rm -f etc/standards.info
sed -i.bak '/^INFO/s/standards.info //' etc/Makefile.in

# Binutils needs a separate build directory:
rm -rf ../binutils-build
mkdir ../binutils-build
cd ../binutils-build

CFLAGS="$DCFLAGS" \
../binutils-${V}/configure \
 --prefix=/usr \
 --infodir=/usr/info \
 --mandir=/usr/man \
 --with-doc-dir=/usr/doc/binutils-${V} \
 --enable-shared \
 --enable-gold=yes \
 --enable-ld=default \
 --enable-lto \
 --enable-64-bit-bfd \
 --enable-targets=$TYPE \
 --enable-plugins \
 --enable-threads \
 --build=$TYPE

make $JOBS
if [[ -n $CHECK ]]; then
  make check;
fi
make install DESTDIR=$PKG

# Set ld to "ld.bfd" or "ld.gold":
( cd ${PKG}/usr/bin
  rm -vf ld
  ln -sf ld.bfd ld
)

# Move ldscripts under usr/lib directory:
mv ${PKG}/usr/${TYPE}/lib/ldscripts ${PKG}/usr/lib

# Creates the corresponding symlinks:
mkdir -p ${PKG}/usr/${TYPE}/{lib,bin}
( cd ${PKG}/usr/${TYPE}/lib
  ln -sf /usr/lib/ldscripts . )
( cd ${PKG}/usr/${TYPE}/bin
  for target in ${PKG}/usr/bin/* ; do
    ln -sf /usr/bin/${target##*/} .
  done
)

# Strip commentaries and notes:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --remove-section=.comment --remove-section=.note 2>/dev/null
)

# Back to the source:
cd -

# Include the Libiberty missing header:
cp -p include/libiberty.h ${PKG}/usr/include

# Compress manuals:
( cd ${PKG}/usr
  rm -f info/dir # Redundancy
  gzip -9N info/* man/man?/*
  # Link this page:
  ( cd man/man1 ; ln -sf c++filt.1.gz cxxfilt.1.gz )
)

# Add the documentation:
mkdir -p ${PKG}/usr/doc/binutils-${V}
cp -a COPYING* README ${PKG}/usr/doc/binutils-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/binutils-${V}-${ARCH}-${B}.tlz

