#!/bin/bash
#  Copyright (C) 2010-2012  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=2.02.95
ARCH=${ARCH:-x86_64}
B=1

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j4}

PKG=${TMP}/package-lvm2

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/LVM2.${V}
tar xvf ${CWD}/LVM2.${V}.tar.lz -C $TMP

cd ${TMP}/LVM2.${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

./configure \
 --prefix=/usr \
 --libdir=/usr/lib64 \
 --with-usrlibdir=/usr/lib64 \
 --sysconfdir=/etc \
 --mandir=/usr/man \
 --enable-pkgconfig \
 --enable-applib \
 --enable-cmdlib \
 --enable-dmeventd \
 --with-lvm1=internal \
 --enable-udev_sync \
 --enable-udev_rules \
 --with-udev-prefix="" \
 --with-device-uid=0 \
 --with-device-gid=8 \
 --with-device-mode=0664 \
 --disable-selinux \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS
make install DESTDIR=$PKG

# Fix permissions:
( cd ${PKG}/usr
  find lib64/ . -type f -perm 555 | xargs chmod 755
  find . -type f -perm 444 | xargs chmod 644
)

# Increments a little the security:
for file in ${PKG}/usr/sbin/* ; do
  [[ -x $file && ! -L $file ]] && chmod -v 750 $file
done

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

# Handle config file:
mv ${PKG}/etc/lvm/lvm.conf{,.new}

# Move man pages under the right location:
if [[ -d ${PKG}/usr/share/man ]]; then
  mv ${PKG}/usr/share/man ${PKG}/usr
  rmdir -p ${PKG}/usr/share/man || true;
fi

# Compress and link manpages:
( cd $PKG/usr/man
  find . -type f -exec gzip -9N '{}' +
  find . -type l | while read file ; do
    ln -sf $(readlink $file).gz ${file}.gz
    rm $file
  done
)

# Add the documentation:
mkdir -p ${PKG}/usr/doc/lvm2-${V}
cp -a \
 COPYING* README VERSION* WHATS_NEW* \
 ${PKG}/usr/doc/lvm2-${V}

# Copy the description files:
mkdir -p ${PKG}/{description,install}
cp ${CWD}/description/* ${PKG}/description

# Add post-install script:
zcat ${CWD}/post-install.gz > ${PKG}/install/post-install

cd $PKG
makepkg -l ${OUT}/lvm2-${V}-${ARCH}-${B}.tlz

