#!/bin/bash
#  Copyright (C) 2010-2011  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=0.23
ARCH=${ARCH:-i486}
B=5

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -march=i486 -mtune=i686}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j4}

PKG=${TMP}/package-obexftp

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/obexftp-${V}
lzip -cd ${CWD}/sources/obexftp-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/obexftp-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

zcat ${CWD}/ruby_wrap.rstring.diff.gz | patch -p0 --verbose

CFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --mandir=/usr/man \
 --disable-static \
 --enable-tcl \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS
make install DESTDIR=$PKG

if [[ -r ${PKG}/usr/bin/obexftpd ]]; then
  mkdir -p ${PKG}/usr/sbin
  mv ${PKG}/usr/bin/obexftpd ${PKG}/usr/sbin/
fi
chmod -v 0750 ${PKG}/usr/sbin/obexftpd

# This is from the spec:
( cd ${PKG}/usr/bin
  for name in obexls obexget obexput obexrm ; do
    ln -sf obexftp $name
  done
)

# Remove the temporary directory from the inventory file of Perl:
perlVersion=$(eval $(perl -V:version); printf "$version")

find ${PKG}/usr -type f -name '.packlist' -exec \
 sed -i "s#$PKG##g" '{}' +

find ${PKG}/usr -type f -name 'perllocal.pod' -delete

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

gzip -9N ${PKG}/usr/man/man?/*.?  # Compress manpages.

# Add the documentation:
mkdir -p ${PKG}/usr/doc/obexftp-${V}
cp -a \
 AUTHORS COPYING* ChangeLog NEWS README THANKS TODO \
 ${PKG}/usr/doc/obexftp-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/descriptions/obexftp/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/obexftp-${V}-${ARCH}-${B}.tlz

