#!/bin/bash
#  Copyright (C) 2010-2011  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=5.9
TAG=20110702
TERMCAP_DATE=20111112
ARCH=${ARCH:-x86_64}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -mtune=generic}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j4}

PKG=${TMP}/package-ncurses

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/ncurses-${V}
tar -xvf ${CWD}/ncurses-${V}.tar.lz -C $TMP

cd ${TMP}/ncurses-${V}

# Apply official patches:
for patch in ${CWD}/patches/*.patch.gz ; do
  if [[ -f $patch ]]; then
    zcat $patch | patch -p1 --verbose
  fi
done

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

CFLAGS="$DCFLAGS" \
CXXFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --libdir=/usr/lib64 \
 --with-shared \
 --with-normal \
 --without-debug \
 --without-ada \
 --enable-widec \
 --enable-symlinks \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS
make install DESTDIR=$PKG

# Move the libraries to the lib directory, where they are expected to reside:
( cd $PKG ; mkdir -p lib64 ; mv usr/lib64/libncursesw.so.5* lib64/ )
# Because the libraries have been moved, one symlink points to a non-existent
# file.  We need to recreate it:
( cd ${PKG}/usr/lib64 ; ln -sf ../../lib64/libncursesw.so.5 libncursesw.so )

# Many applications still expect the linker to be able to find non-wide-character:
for lib in ncurses form panel menu ; do \
  rm -f ${PKG}/usr/lib64/lib${lib}.so ; \
  echo "INPUT(-l${lib}w)" > ${PKG}/usr/lib64/lib${lib}.so
  ln -sf lib${lib}w.a ${PKG}/usr/lib64/lib${lib}.a
done
( cd ${PKG}/usr/lib64 ; ln -sf libncurses++w.a libncurses++.a )

# Backward compatibility:
rm -f ${PKG}/usr/lib64/libcursesw.so
( cd ${PKG}/usr/lib64
  echo "INPUT(-lncursesw)" > libcursesw.so
  ln -sf libncurses.so libcurses.so
  ln -sf libncursesw.a libcursesw.a
  ln -sf libncurses.a libcurses.a
)

# Make extra support:
make clean

CFLAGS="$DCFLAGS" \
CXXFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --with-shared \
 --without-normal \
 --without-debug \
 --without-cxx-binding \
 --without-ada \
 --enable-symlinks \
 --build=${ARCH}-dragora-linux-gnu

make sources libs
cp -a lib/lib*.so.5* ${PKG}/usr/lib64

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
  find . -type f | xargs file | awk '/current ar archive/' | \
   cut -f 1 -d : | xargs strip --strip-debug 2> /dev/null
)

# Include the termcap file provided by Thomas E. Dickey:
mkdir -p ${PKG}/etc
lzip -cd ${CWD}/termcap-${TERMCAP_DATE}.src.lz > ${PKG}/etc/termcap.new

# Copy the documentation:
mkdir -p ${PKG}/usr/doc/ncurses-${V}
cp -a \
 ANNOUNCE AUTHORS NEWS README TO-DO \
 ${PKG}/usr/doc/ncurses-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/?? ${PKG}/description

# Add the post install script:
mkdir -p ${PKG}/install
zcat ${CWD}/post-install.gz > ${PKG}/install/post-install

cd $PKG
makepkg -l ${OUT}/ncurses-${V}_${TAG}-${ARCH}-${B}.tlz

