#!/bin/bash
#  Copyright (C) 2011  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

P=wqy-zenhei
V=${V:-0.8.38-1}
V2=${V%-*}
ARCH=noarch
B=${B:-1}

PKG=${TMP}/package-${P}

rm -rf $PKG
mkdir -p $PKG $OUT

rm -rf ${TMP}/${P}-${V}
echo "Uncompressing the tarball..."
tar -xvf ${CWD}/${P}-${V}.tar.lz -C "$TMP"

cd ${TMP}/${P}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \
 \) -exec chmod 755 {} + \
 -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \
 \) -exec chmod 644 {} +

# Make the package structure:
mkdir -p ${PKG}/usr/share/fonts/X11/wqy-zenhei
cp -a \
 *.conf *.ttc zenheiset \
 ${PKG}/usr/share/fonts/X11/wqy-zenhei

mkdir -p ${PKG}/etc/fonts/conf.avail
cp -a 44-wqy-zenhei.conf ${PKG}/etc/fonts/conf.avail

# Copy the documentation:
mkdir -p ${PKG}/usr/doc/${P}-${V2}
cp -a \
 AUTHORS COPYING ChangeLog README \
 ${PKG}/usr/doc/${P}-${V2}

cd $PKG

# Copy the description files:
mkdir -p description
cp ${CWD}/description/?? description/

# Build the package:
makepkg -l ${OUT}/${P}-${V2}-${ARCH}-${B}.tlz

