#!/bin/bash
#  Copyright (C) 2010-2011  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=2.11.0
ARCH=${ARCH:-x86_64}
B=1

PKG=${TMP}/package-xerces-j

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
cd $TMP
rm -rf xerces-j-${V}
lzip -cd ${CWD}/Xerces-J-src.${V}.tar.lz | tar -xvf -
mv xerces-$(printf "$V" | tr . _) xerces-j-${V}

cd xerces-j-${V}

# Required:
lzip -cd ${CWD}/Xerces-J-tools.${V}.tar.lz | tar -xvf -

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

# Build and install xerces-j:
sed -i 's/.$//' build.sh  # From DOS to Unix format.
sh build.sh jars

install -d ${PKG}/usr/share/java
install -m 644 build/*.jar ${PKG}/usr/share/java/

# Add the documentation:
mkdir -p ${PKG}/usr/doc/xerces-j-${V}
cp -a \
 LICENSE* NOTICE* Readme.html \
 ${PKG}/usr/doc/xerces-j-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/xerces-j-${V}-${ARCH}-${B}.tlz

