#!/bin/bash
#  Copyright (C) 2010-2011  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=1.10.0
ARCH=${ARCH:-x86_64}
B=2

PKG=${TMP}/package-py2cairo

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/py2cairo-${V}
lzip -cd ${CWD}/py2cairo-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/py2cairo-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

./waf configure --prefix=/usr --libdir=/usr/lib64
./waf build
./waf install --destdir=$PKG

# Move Python files to /usr/lib:
mkdir -p ${PKG}/usr/lib
( cd ${PKG}/usr
  mv lib64/python?.?* lib/
)

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || :
)

# Add the documentation:
mkdir -p ${PKG}/usr/doc/py2cairo-${V}
cp -a \
 AUTHORS COPYING* NEWS README \
 ${PKG}/usr/doc/py2cairo-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/?? ${PKG}/description

cd $PKG
makepkg -l ${OUT}/py2cairo-${V}-${ARCH}-${B}.tlz

