#!/bin/bash
#  Copyright (C) 2010-2012  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=1.10_20110608
ARCH=${ARCH:-x86_64}
B=2

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -mtune=generic}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j5}

PKG=${TMP}/package-cairo

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/cairo-${V}
lzip -cd ${CWD}/cairo-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/cairo-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

# Reference:
# http://bugs.gentoo.org/show_bug.cgi?id=336696
zcat ${CWD}/cairo-1.10.0-buggy_gradients.patch.gz | patch -p1 --verbose

chmod +x ./autogen.sh

export CFLAGS="$DCFLAGS" CXXFLAGS="$DCFLAGS"

./autogen.sh \
 --prefix=/usr \
 --sysconfdir=/etc \
 --mandir=/usr/man \
 --libdir=/usr/lib64 \
 --localstatedir=/var \
 --disable-static \
 --disable-quartz \
 --disable-win32 \
 --disable-gtk-doc \
 --enable-qt=no \
 --enable-ps=yes \
 --enable-pdf=yes \
 --enable-png=yes \
 --enable-svg=yes \
 --enable-ft=yes \
 --enable-tee=yes \
 --enable-gobject=yes \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS
make install DESTDIR=$PKG

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

# Compress manpage(s) -- if needed:
if [[ -d ${PKG}/usr/man ]]; then
  gzip -9N ${PKG}/usr/man/man?/*.?
fi

# Add the documentation:
mkdir -p ${PKG}/usr/doc/cairo-${V}
cp -a \
 AUTHORS BIBLIOGRAPHY BUGS CODING_STYLE COPYING* ChangeLog \
 HACKING NEWS PORTING_GUIDE README RELEASING \
 ${PKG}/usr/doc/cairo-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/cairo-${V}-${ARCH}-${B}.tlz

