#!/bin/bash
#  Copyright (C) 2010-2011  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=3.0.12
ARCH=${ARCH:-x86_64}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -mtune=generic}

PKG=${TMP}/package-dosfstools

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/dosfstools-${V}
lzip -cd ${CWD}/dosfstools-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/dosfstools-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

make CFLAGS="$DCFLAGS"
make install \
 PREFIX=$PKG \
 MANDIR=${PKG}/usr/man \
 DOCDIR=${PKG}/usr/doc/dosfstools-${V}

strip --strip-unneeded ${PKG}/sbin/* 2> /dev/null || true;

# Increment a little the security:
find ${PKG}/sbin -type f | xargs chmod -v 0750

# Compress and link manpages:
( cd ${PKG}/usr/man
  find . -type f -exec gzip -9N '{}' +
  find . -type l | while read file ; do
    ln -sf $(readlink $file).gz ${file}.gz
    rm $file
  done
)

# Re-copy the documentation:
rm -rf ${PKG}/usr/doc/dosfstools-${V}/dosfstools
mkdir -p ${PKG}/usr/doc/dosfstools-${V}
cp -a \
 COPYING ChangeLog doc/* \
 ${PKG}/usr/doc/dosfstools-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/dosfstools-${V}-${ARCH}-${B}.tlz

