#!/bin/bash
#  Copyright (C) 2010  Matías A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=3.17
ARCH=${ARCH:-i486}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -march=i486 -mtune=i686}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j2}

PKG=${TMP}/package-quota-tools

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/quota-tools-${V}
lzip -cd ${CWD}/quota-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/quota-tools

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

CFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --sysconfdir=/etc/quota \
 --mandir=/usr/man \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS
make install ROOTDIR=$PKG

# Headers included on the glibc package:
rm -v ${PKG}/usr/include/rpcsvc/rquota.?

# Fix permissions:
chmod 755 ${PKG}/usr/bin/quota

# Increments a little the security:
for file in ${PKG}/usr/sbin/* ; do
  if [[ -f $file && -x $file ]]; then
    chmod -v 750 $file
  fi
done

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip -s 2> /dev/null
)

# Move sample configs:
for file in ${PKG}/etc/quota/* ; do
  mv $file ${file}-sample
done

# Fix permissions of the manpages:
find ${PKG}/usr/man -type f | xargs chmod 644

# Compress and link manpages:
( cd ${PKG}/usr/man
  find . -type f -exec gzip -9N '{}' +
  find . -type l | while read file ; do
    ln -sf $(readlink $file).gz ${file}.gz
    rm $file
  done
)

# Page included on the glibc package:
rm -f ${PKG}/usr/man/man2/quotactl.2.gz

# Add the documentation:
mkdir -p ${PKG}/usr/doc/quota-tools-${V}
cp -a \
 Changelog README* \
 ${PKG}/usr/doc/quota-tools-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/quota-tools-${V}-${ARCH}-${B}.tlz

