#!/bin/bash
#  Copyright (C) 2010  Matías A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=0.8.90
ARCH=${ARCH:-x86_64}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -fPIC}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j4}

PKG=${TMP}/package-icon-naming-utils

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/icon-naming-utils-${V}
lzip -cd ${CWD}/icon-naming-utils-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/icon-naming-utils-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

./configure \
 --prefix=/usr \
 --libdir=/usr/lib64 \
 --libexecdir=/usr/bin \
 --build=${ARCH}-dragora-linux-gnu

make
make install DESTDIR=$PKG

# Move pkgconfig directory to the right location:
if [[ -d ${PKG}/usr/share/pkgconfig ]]; then
  mkdir -p ${PKG}/usr/lib64
  mv ${PKG}/usr/share/pkgconfig ${PKG}/usr/lib64
fi

# Add the documentation:
mkdir -p ${PKG}/usr/doc/icon-naming-utils-${V}
cp -a \
 AUTHORS COPYING ChangeLog NEWS README \
 ${PKG}/usr/doc/icon-naming-utils-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg ${OUT}/icon-naming-utils-${V}-${ARCH}-${B}.tlz

