#!/bin/bash
#  Copyright (C) 2010-2011  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=2.8.6
ARCH=${ARCH:-i486}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -march=i486 -mtune=i686}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j4}

PKG=${TMP}/package-fuse

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/fuse-${V}
lzip -cd ${CWD}/fuse-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/fuse-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

CFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --bindir=/bin \
 --libdir=/lib \
 --localstatedir=/var \
 --disable-static \
 --with-pkgconfigdir=/usr/lib/pkgconfig \
 --enable-lib \
 --enable-util \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS
make install DESTDIR=$PKG \
 UDEV_RULES_PATH=/lib/udev/rules.d INIT_D_PATH=/etc/rc.d

rm -rf ${PKG}/dev  ## Already handled by udev.

# To handle config file:
( cd ${PKG}/etc/rc.d
  mv fuse rc.fuse.new
  chmod 755 rc.fuse.new
)

# Increments a little the security:
chmod -v 0750 ${PKG}/sbin/mount.fuse

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

# Add the documentation:
mkdir -p ${PKG}/usr/doc/fuse-${V}
cp -a \
 AUTHORS COPYING* FAQ Filesystems NEWS README* \
 doc/how-fuse-works doc/kernel.txt \
 ${PKG}/usr/doc/fuse-${V}

# Add the post-install script:
mkdir -p ${PKG}/install
zcat ${CWD}/post-install.gz > ${PKG}/install/post-install

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/fuse-${V}-${ARCH}-${B}.tlz

