#!/bin/bash
#  Copyright (C) 2010-2012  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=278
ARCH=${ARCH:-x86_64}
B=2

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -mtune=generic}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j5}

PKG=${TMP}/package-xterm

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/xterm-${V}
lzip -cd ${CWD}/xterm-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/xterm-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

CFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --sysconfdir=/etc \
 --mandir=/usr/man \
 --with-app-defaults=/etc/X11/app-defaults \
 --with-pcre \
 --enable-exec-xterm \
 --enable-256-color \
 --enable-88-color \
 --enable-luit \
 --enable-wide-chars \
 --disable-full-tgetent \
 --disable-imake \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS
make install DESTDIR=$PKG
# Some files are provided by ncurses:
#make install-ti DESTDIR=$PKG

# Move the terminfo directory to the right location:
if [[ -d ${PKG}/usr/lib/terminfo ]]; then
  mkdir -p ${PKG}/usr/share
  mv ${PKG}/usr/lib/terminfo ${PKG}/usr/share
fi

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

# Include the desktop entry:
mkdir -p ${PKG}/usr/share/applications
cat xterm.desktop > ${PKG}/usr/share/applications/xterm.desktop

# Compress manpages (if exists):
if [[ -d ${PKG}/usr/man ]]; then
  for manpage in ${PKG}/usr/man/man?/*.? ; do
    gzip -9N $manpage
  done
fi

# Add the documentation:
mkdir -p ${PKG}/usr/doc/xterm-${V}
cp -a \
 AAA_README_VMS.txt README README.i18n THANKS \
 ${PKG}/usr/doc/xterm-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/xterm-${V}-${ARCH}-${B}.tlz

