#!/bin/bash
#  Copyright (C) 2009-2010  Matías A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=3.2.8
ARCH=${ARCH:-i486}
B=2

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2}

PKG=${TMP}/package-procps

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/procps-${V}
tar xvf ${CWD}/procps-${V}.tar.lz -C $TMP

cd ${TMP}/procps-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

# Apply a patch to prevent an error message from being displayed
# when determining the kernel clock tick rate (thanks to LFS): 
zcat ${CWD}/patches/procps-3.2.8-fix_HZ_errors-1.patch.gz | patch -p1 --verbose

# Apply a patch to fix a unicode related issue in the watch program: 
zcat ${CWD}/patches/procps-3.2.8-watch_unicode-1.patch.gz | patch -p1 --verbose

# Fix a bug in the Makefile, which prevents
# procps from building with make-3.82: 
sed -i -e 's@\*/module.mk@proc/module.mk ps/module.mk@' Makefile

# Changes the location of the man-pages:
sed -i 's|/usr/share/man|/usr/man|g' Makefile

make CFLAGS="$DCFLAGS"
make install DESTDIR=$PKG

# Increments a little the security:
find ${PKG}/sbin -type f | xargs chmod -v 750
# Just in case:
if [[ -d ${PKG}/usr/sbin ]]; then
  find ${PKG}/usr/sbin -type f | xargs chmod -v 750
fi

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

# Compress and link some man-pages:
gzip -9N ${PKG}/usr/man/man?/*
( cd ${PKG}/usr/man/man1
  ln -sf skill.1.gz snice.1.gz
  ln -sf pgrep.1.gz pkill.1.gz
)

# Add the documentation:
mkdir -p ${PKG}/usr/doc/procps-${V}
cp -a \
 AUTHORS BUGS COPYING* NEWS README* TODO procps.lsm \
 ${PKG}/usr/doc/procps-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/procps-${V}-${ARCH}-${B}.tlz

