#!/bin/bash
#  Copyright (C) 2010-2011  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=${V:-0.90}
ARCH=${ARCH:-i486}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-Os}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j2}

PKG=${TMP}/package-shared-mime-info

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/shared-mime-info-${V}
tar -xvf ${CWD}/shared-mime-info-${V}.tar.lz -C $TMP

cd ${TMP}/shared-mime-info-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

CFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --mandir=/usr/man \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS
make install DESTDIR=$PKG

# Oh, shit -- again, again, again!.
#
# Move the pkgconfig directory to the right localtion:
if [[ -d ${PKG}/usr/share/pkgconfig ]]; then
  mkdir -p ${PKG}/usr/lib
  mv ${PKG}/usr/share/pkgconfig ${PKG}/usr/lib
fi

strip --strip-unneeded ${PKG}/usr/bin/update-mime-database
gzip -9N ${PKG}/usr/man/man1/update-mime-database.1

# Add the documentation:
mkdir -p ${PKG}/usr/doc/shared-mime-info-${V}
cp -a \
 COPYING ChangeLog HACKING NEWS README \
 ${PKG}/usr/doc/shared-mime-info-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/?? ${PKG}/description

cd $PKG
makepkg -l ${OUT}/shared-mime-info-${V}-${ARCH}-${B}.tlz

