#!/bin/bash
#  Copyright (C) 2010, 2012  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=1.2.10
ARCH=${ARCH:-x86_64}
B=2

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -mtune=generic}

PKG=${TMP}/package-glib

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/glib-${V}
tar xvf ${CWD}/glib-${V}.tar.lz -C $TMP

cd ${TMP}/glib-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

zcat ${CWD}/glib1.2_1.2.10-19.diff.gz | patch -p1 --verbose

CFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --libdir=/usr/lib64 \
 --infodir=/usr/info \
 --mandir=/usr/man \
 --localstatedir=/var \
 --disable-static \
 --program-prefix="" \
 --program-suffix="" \
 --build=${ARCH}-dragora-linux-gnu

make
make install DESTDIR=$PKG

# Fix library permission:
chmod -c a+x ${PKG}/usr/lib64/libgmodule-1.2.so.0.0.10

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

# Compress GNU info documents:
( cd ${PKG}/usr/info ; rm -f dir ; gzip -9N * )

# Compress man-pages:
gzip -9N ${PKG}/usr/man/man?/*.?

# Add the documentation:
mkdir -p ${PKG}/usr/doc/glib-${V}
cp -a \
 AUTHORS COPYING ChangeLog NEWS README \
 ${PKG}/usr/doc/glib-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/glib-${V}-${ARCH}-${B}.tlz

