#!/bin/bash
#  Copyright (C) 2010  Matias A. Fonzo, <selk@dragora.org>
#  Copyright (C) 2011  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=2.5.35
ARCH=${ARCH:-x86_64}
B=2

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -mtune=generic}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j4}

PKG=${TMP}/package-flex

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/flex-${V}
tar xvf ${CWD}/flex-${V}.tar.lz -C $TMP

cd ${TMP}/flex-${V}

# Apply a patch that fixes a bug in the C++ scanner generator,
# that causes scanner compilation to fail when using
# GCC-4.4.2 (thanks to LFS):
zcat ${CWD}/patches/flex-2.5.35-gcc44-1.patch.gz | patch -p1 --verbose

# Fix redundant redeclaration of 'isatty':
#
# http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=488274
zcat ${CWD}/patches/isatty.patch.gz | patch -p0 --verbose

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

CFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --libdir=/usr/lib64 \
 --localstatedir=/var \
 --infodir=/usr/info \
 --mandir=/usr/man \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS
if [[ -n $CHECK ]]; then
  make check;
fi
make install DESTDIR=$PKG

strip --strip-unneeded ${PKG}/usr/bin/flex
strip --strip-debug ${PKG}/usr/lib64/*.a

# Make compatibility with the original "lex":
cat << "EOF" > ${PKG}/usr/bin/lex
#!/bin/sh
exec /usr/bin/flex -l "$@"

EOF

chmod 755 ${PKG}/usr/bin/lex
( cd ${PKG}/usr/lib64 ; ln -sf libfl.a libl.a )

# Compress manuals (.info documents and man-pages):
( cd ${PKG}/usr ; rm -f info/dir ; gzip -9N info/* man/man?/* )

# Add the documentation:
mkdir -p ${PKG}/usr/doc/flex-${V}
cp -a \
 ABOUT-NLS AUTHORS COPYING ChangeLog NEWS README* TODO THANKS \
 ${PKG}/usr/doc/flex-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/flex-${V}-${ARCH}-${B}.tlz

