#!/bin/bash
#  Copyright (C) 2010-2011  Matías A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=0.9
ARCH=${ARCH:-i486}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -march=i486 -mtune=i686}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j4}

PKG=${TMP}/package-mpc

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/mpc-${V}
lzip -cd ${CWD}/mpc-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/mpc-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

zcat ${CWD}/configure.ac.diff.gz | patch -p1 --verbose

autoreconf

CFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --enable-shared \
 --enable-static \
 --localstatedir=/var \
 --infodir=/usr/info \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS || make;
if [[ -n $CHECK ]]; then
  make check;
fi
make install DESTDIR=$PKG

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)
strip --strip-debug ${PKG}/usr/lib/*.a

# Compress .info pages:
rm -f ${PKG}/usr/info/dir  # Redundancy.
gzip -9N ${PKG}/usr/info/*

# Add the documentation:
mkdir -p ${PKG}/usr/doc/mpc-${V}
cp -a \
 AUTHORS COPYING.LIB ChangeLog NEWS README TODO \
 ${PKG}/usr/doc/mpc-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/mpc-${V}-${ARCH}-${B}.tlz

