#!/bin/bash
#  Copyright (C) 2010-2012  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=3.8.0cvs39
ARCH=${ARCH:-i486}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -march=i486 -mtune=i686}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j5}

PKG=${TMP}/package-claws-mail

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/claws-mail-${V}
tar -xvf ${CWD}/claws-mail-${V}.tar.lz -C $TMP

cd ${TMP}/claws-mail-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

CFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --sysconfdir=/etc \
 --mandir=/usr/man \
 --docdir=/usr/doc/claws-mail-${V} \
 --with-manualdir=/usr/doc/claws-mail-${V}/html \
 --localstatedir=/var \
 --disable-static \
 --enable-shared \
 --enable-libetpan \
 --enable-gnutls \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS
make install DESTDIR=$PKG

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

# Compress man page(s):
gzip -9N ${PKG}/usr/man/man?/*.?

# Copy the rest of the documentation:
mkdir -p ${PKG}/usr/doc/claws-mail-${V}
cp -a \
 ABOUT-NLS AUTHORS COPYING ChangeLog NEWS README RELEASE_NOTES TODO \
 ${PKG}/usr/doc/claws-mail-${V}

# Add the rest for the package:
mkdir -p ${PKG}/{description,install}
cp ${CWD}/description/?? ${PKG}/description
zcat ${CWD}/post-install.gz > ${PKG}/install/post-install

cd $PKG
makepkg -l ${OUT}/claws-mail-${V}-${ARCH}-${B}.tlz

