#!/bin/bash
#  Copyright (C) 2010  Matías A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=5.0.5
ARCH=${ARCH:-x86_64}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -fPIC}

PKG=${TMP}/package-whois

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/whois-${V}
lzip -cd ${CWD}/whois_${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/whois-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

make CFLAGS="$DCFLAGS" HAVE_LIBIDN=1 HAVE_ICONV=1

# Install manually:
#
#make install-whois BASEDIR=$PKG

# Install binaries and manpages:
install -m 755 whois -D ${PKG}/usr/bin/whois
install -m 755 mkpasswd -D ${PKG}/usr/bin/mkpasswd
(
  cd ${PKG}/usr/bin
  strip -s whois mkpasswd
)
install -m 644 whois.1 -D ${PKG}/usr/man/man1/whois.1
install -m 644 mkpasswd.1 -D ${PKG}/usr/man/man1/mkpasswd.1
(
  cd ${PKG}/usr/man/man1
  gzip -9 whois.1 mkpasswd.1
)

# Make and install locales:
cd po/
make
for file in *.mo ; do
  name=${file%.mo}
  mkdir -p ${PKG}/usr/share/locale/${name}/LC_MESSAGES
  cp $file ${PKG}/usr/share/locale/${name}/LC_MESSAGES/whois.mo
done
cd -

# Add the documentation:
mkdir -p ${PKG}/usr/doc/whois-${V}
cp -a \
 COPYING README \
 ${PKG}/usr/doc/whois-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/whois-${V}-${ARCH}-${B}.tlz

