#!/bin/bash
#  Copyright (C) 2010  Matías A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=1.20
ARCH=${ARCH:-i486}
B=1

PKG=${TMP}/package-mutagen

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/mutagen-${V}
tar -xvf ${CWD}/mutagen-${V}.tar.lz -C $TMP

cd ${TMP}/mutagen-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

python setup.py install \
 --prefix=/usr \
 --root=$PKG

# Move man pages under usr/man:
if [[ -d ${PKG}/usr/share/man ]]; then
  ( cd ${PKG}/usr/share ; mv man/ ../ )
  rmdir ${PKG}/usr/share || true;
fi

# Compress man page(s):
gzip -9N ${PKG}/usr/man/man?/*.?

# Add the documentation:
mkdir -p ${PKG}/usr/doc/mutagen-${V}
cp -a \
 API-NOTES COPYING NEWS PKG-INFO README TODO TUTORIAL \
 ${PKG}/usr/doc/mutagen-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/?? ${PKG}/description

cd $PKG
makepkg -l ${OUT}/mutagen-${V}-${ARCH}-${B}.tlz

