#!/bin/bash
#  Copyright (C) 2009, 2012  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=20111217
ARCH=${ARCH:-i486}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -march=i486 -mtune=i686}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j4}

PKG=${TMP}/package-module-init-tools

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/module-init-tools-${V}
lzip -cd ${CWD}/module-init-tools-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/module-init-tools-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +


zcat ${CWD}/module-init-tools-3.16-man_pages-1.patch.gz | patch -p1 --verbose

aclocal -I m4
automake --add-missing --copy
autoconf

CFLAGS="$DCFLAGS" \
./configure \
 --prefix=/ \
 --mandir=/usr/man \
 --enable-zlib \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS
make INSTALL=install install DESTDIR=$PKG

# Increments a little the security:
find ${PKG}/sbin -type f | xargs chmod -v 750

# Strip binaries & libraries (if any):
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

# Empty dir for modules aliases:
mkdir -p ${PKG}/etc/modprobe.d

# Compress man-pages:
gzip -9N ${PKG}/usr/man/man?/*

# Add the documentation:
mkdir -p ${PKG}/usr/doc/module-init-tools-${V}
cp -a \
 AUTHORS CODING COPYING ChangeLog FAQ NEWS README TODO \
 ${PKG}/usr/doc/module-init-tools-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/module-init-tools-${V}-${ARCH}-${B}.tlz

