#!/bin/bash
#  Copyright (C) 2010  Matías A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=0.12
ARCH=noarch
B=1

PKG=${TMP}/package-hicolor-icon-theme

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/hicolor-icon-theme-${V}
lzip -cd ${CWD}/hicolor-icon-theme-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/hicolor-icon-theme-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

./configure --prefix=/usr

make
make install DESTDIR=$PKG

# Add the documentation:
mkdir -p ${PKG}/usr/doc/hicolor-icon-theme-${V}
cp -a \
 COPYING ChangeLog README \
 ${PKG}/usr/doc/hicolor-icon-theme-${V}
find ${PKG}/usr/doc/hicolor-icon-theme-${V} -type f | xargs chmod 644

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/hicolor-icon-theme-${V}-${ARCH}-${B}.tlz

