#!/bin/bash
#  Copyright (C) 2010  Matías A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=0.16.17
ARCH=${ARCH:-x86_64}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -fPIC}

PKG=${TMP}/package-dev86

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/dev86-${V}
tar xvf ${CWD}/Dev86src-${V}.tar.lz -C $TMP

cd ${TMP}/dev86-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

# Compile for 64-bit:
zcat ${CWD}/dev86-pic.patch.gz | patch -p0 --verbose

sed -i.orig \
 -e 's#alt-libs elksemu#alt-libs#' \
 -e 's#install-lib install-emu#install-lib#' \
  makefile.in

# Compile with our cflags:
sed -i -e "s/-O2 -g/${DFLAGS}/" makefile.in

# Fix library path:
#sed -i \
# -e 's#LIBDIR=  $(PREFIX)/lib/bcc#LIBDIR=  $(PREFIX)/lib64/bcc#' \
# -e 's#INCLDIR= $(PREFIX)/lib/bcc#INCLDIR= $(PREFIX)/lib64/bcc#' \
#  Makefile

echo 'quit' | make
make install DIST=$PKG

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip -s 2> /dev/null
  find . -type f | xargs file | awk '/current ar archive/' | \
   cut -f 1 -d : | xargs strip -g 2> /dev/null
)

# Compress man-pages:
gzip -9N ${PKG}/usr/man/man?/*

# Add the documentation:
mkdir -p ${PKG}/usr/doc/dev86-${V}
cp -a \
 COPYING Changes Contributors README \
 ${PKG}/usr/doc/dev86-${V}

# Add extra documentation:
for dir in bootblocks copt dis88 elksemu unproto ; do
  if [[ -r ${dir}/README ]]; then
    cp -a ${dir}/README ${PKG}/usr/doc/dev86-${V}/README.${dir}
  fi
done


# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/dev86-${V}-${ARCH}-${B}.tlz

