#!/bin/bash
#  Copyright (C) 2010-2011  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=1.13.4
ARCH=${ARCH:-x86_64}
B=2

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -mtune=generic}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j4}

PKG=${TMP}/package-wget

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/wget-${V}
tar xvf ${CWD}/wget-${V}.tar.lz -C $TMP

cd ${TMP}/wget-${V}

# Apply patch:$
patch -p1 -i ${CWD}/patches/CVE-2014-4877.patch$

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

CFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --sysconfdir=/etc/wget \
 --mandir=/usr/man \
 --infodir=/usr/info \
 --localstatedir=/var \
 --disable-debug \
 --with-ssl=openssl \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS
make install DESTDIR=$PKG

strip --strip-unneeded ${PKG}/usr/bin/wget

mv ${PKG}/etc/wget/wgetrc{,.sample}

# Compress GNU info documents:
( cd ${PKG}/usr/info ; rm -f dir ; gzip -9N * )

# Compress man-pages:
gzip -9N ${PKG}/usr/man/man?/*

# Add the documentation:
mkdir -p ${PKG}/usr/doc/wget-${V}
cp -a \
 AUTHORS COPYING ChangeLog ChangeLog.README MAILING-LIST NEWS README \
 ${PKG}/usr/doc/wget-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/wget-${V}-${ARCH}-${B}.tlz

