#!/bin/bash
#  Copyright (C) 2010, 2011  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=1.2.10
ARCH=${ARCH:-i486}
B=3

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -march=i486 -mtune=i686}

PKG=${TMP}/package-gtk1+-1

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/gtk+-${V}
lzip -cd ${CWD}/gtk+-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/gtk+-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

# Apply a patch from Debian:
zcat ${CWD}/patches/gtk+1.2_1.2.10-18.1.diff.gz | patch -p1 --verbose

CFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --sysconfdir=/etc \
 --localstatedir=/var \
 --disable-static \
 --disable-glibtest \
 --with-xinput=xfree \
 ${ARCH}-dragora-linux-gnu

make
make install DESTDIR=$PKG

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

# Make missing symlink for compatibility:
( cd ${PKG}/usr/lib ; ln -sf libgdk-1.2.so.0.9.1 libgdk.so.0 )

if [[ -d ${PKG}/usr/info ]]; then  # Compress manuals -- if needed:
  rm -f ${PKG}/usr/info/dir  # Redundancy.
  gzip -9N ${PKG}/usr/info/*
fi
if [[ -d ${PKG}/usr/man ]]; then  # Compress manpages -- if needed:
  gzip -9N ${PKG}/usr/man/man?/*.?
fi

# Add the documentation:
mkdir -p ${PKG}/usr/doc/gtk1+-${V}
cp -a \
 ABOUT-NLS AUTHORS COPYING ChangeLog HACKING NEWS README* TODO \
 ${PKG}/usr/doc/gtk1+-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/gtk1+-${V}-${ARCH}-${B}.tlz

