#!/bin/bash
#  Copyright (C) 2010-2012  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

P=scrotwm
V=${V:-0.10.0}
ARCH=${ARCH:-x86_64}
B=${B:-1}

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -mtune=generic}

PKG=${TMP}/package-${P}

rm -rf $PKG
mkdir -p $PKG $OUT

rm -rf ${TMP}/${P}-${V}
echo "Uncompressing the tarball..."
tar -xvf ${CWD}/${P}-${V}.tar.lz -C $TMP

cd ${TMP}/${P}-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \
 \) -exec chmod 755 {} + \
 -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \
 \) -exec chmod 644 {} +

sed -i 's#/usr/local/lib/libswmhack.so#/usr/lib64/libswmhack.so#g' scrotwm.c
sed -i 's#$(PREFIX)/lib#$(PREFIX)/lib64#g' linux/Makefile

export CFLAGS+="$DCFLAGS"
pushd linux
  make PREFIX=/usr
  make PREFIX=/usr install DESTDIR=$PKG
popd
( cd ${PKG}/usr/lib64
  ln -sf libswmhack.so.0.0 libswmhack.so
  ln -sf libswmhack.so.0.0 libswmhack.so.0
)
mkdir -p ${PKG}/etc
zcat ${CWD}/scrotwm.conf.gz > ${PKG}/etc/scrotwm.conf.new

# Add scripts:
for file in *.sh ; do
  install -m 755 $file -D ${PKG}/usr/share/scrotwm/${file}
done

# Add the xinitrc entry for scrotwm:
mkdir -p ${PKG}/etc/X11/xinit
zcat ${CWD}/xinitrc-64.gz > ${PKG}/etc/X11/xinit/xinitrc.scrotwm
chmod 755 ${PKG}/etc/X11/xinit/xinitrc.scrotwm
( cd ${PKG}/etc/X11/xinit
  ln -sf xinitrc.scrotwm xinitrc
)

# Reorganize man pages:
if [[ -d ${PKG}/usr/share/man ]]; then
  mv ${PKG}/usr/share/man ${PKG}/usr
  rmdir ${PKG}/usr/share || true;
fi
( cd ${PKG}/usr/man/man1
  for suffix in es it pt ru ; do
    mkdir -p ${PKG}/usr/man/${suffix}/man1
    mv *_${suffix}* ${PKG}/usr/man/${suffix}/man1
  done
)
# Compress the pages:
find ${PKG}/usr/man -type f -exec gzip -9N '{}' +

cd $PKG

# Strip binaries & libraries:
find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
 cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true;

# Copy the description files:
mkdir -p description install
cp ${CWD}/description/?? description/
zcat ${CWD}/post-install.gz > ${PKG}/install/post-install

# Build the package:
makepkg -l ${OUT}/${P}-${V}-${ARCH}-${B}.tlz

