#!/bin/bash
#  Copyright (C) 2010-2012  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=1.7.1
ARCH=${ARCH:-i486}
B=1

PKG=${TMP}/package-wicd

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/wicd-${V}
tar -xvf ${CWD}/wicd-${V}.tar.lz -C $TMP

cd ${TMP}/wicd-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

python setup.py configure \
 --mandir=/usr/man \
 --docdir=/usr/doc/wicd-${V}

python setup.py install --root=$PKG

chmod -v 0750 ${PKG}/usr/sbin/wicd

# No, thanks:
rm -rf ${PKG}/lib/systemd
rmdir ${PKG}/lib || true;

# To Handle config:
( cd ${PKG}/etc/dbus-1/system.d
  mv wicd.conf{,.new}
)

# Add our wicd daemon:
install -v -m 0755 ${CWD}/service/wicd -D ${PKG}/etc/sv/wicd/run.new
install -v -d ${PKG}/etc/runit/runsvdir/default
( cd ${PKG}/etc/runit/runsvdir/default
  ln -sf /etc/sv/wicd .
)

# Compress man page(s):
( cd ${PKG}/usr/man
  find . -type f -name '*.?' | xargs gzip -9N
)

# Add the rests for the package:
mkdir -p ${PKG}/{description,install}
cp ${CWD}/description/?? ${PKG}/description/
zcat ${CWD}/post-install.gz > ${PKG}/install/post-install

# Build the package:
cd $PKG
makepkg -l ${OUT}/wicd-${V}-${ARCH}-${B}.tlz

