#!/bin/bash
#  Copyright (C) 2010  Matías A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=7.1
ARCH=${ARCH:-x86_64}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-m64}

PKG=${TMP}/package-dvd+rw-tools

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/dvd+rw-tools-${V}
tar -xvf ${CWD}/dvd+rw-tools-${V}.tar.lz -C $TMP

cd ${TMP}/dvd+rw-tools-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

zcat ${CWD}/dvd+rw-tools-7.1-headers-1.patch.gz | patch -p1 --verbose

export CFLAGS="$DCFLAGS" CXXFLAGS="$DCFLAGS"
make

for file in \
 dvd+rw-booktype dvd+rw-format dvd+rw-mediainfo dvd-ram-control growisofs
do
 install -m 755 $file -D ${PKG}/usr/bin/$file
done
strip --strip-unneeded ${PKG}/usr/bin/* || true;
install -d ${PKG}/usr/man/man1
gzip -9Nc < growisofs.1 > ${PKG}/usr/man/man1/growisofs.1.gz

# Copy documentation:
mkdir -p ${PKG}/usr/doc/dvd+rw-tools-${V}
cp -a LICENSE keys.txt ${PKG}/usr/doc/dvd+rw-tools-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/?? ${PKG}/description

cd $PKG
makepkg ${OUT}/dvd+rw-tools-${V}-${ARCH}-${B}.tlz

