#!/bin/bash
#  Copyright (C) 2010, 2011  Matias A. Fonzo, <selk@dragora.org>
#  Copyright (C) 2012  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=20111209
ARCH=noarch
B=1

PKG=${TMP}/package-xdg-utils

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/xdg-utils-${V}
lzip -cd ${CWD}/xdg-utils-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/xdg-utils-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

zcat ${CWD}/clean-references.diff.gz | patch -p1 --verbose

./configure --prefix=/usr --sysconfdir=/etc

make
make install DESTDIR=$PKG

gzip -9N ${PKG}/usr/man/man?/*.?  # Compress manpages.

# Add the documentation:
mkdir -p ${PKG}/usr/doc/xdg-utils-${V}
cp -a \
 ChangeLog LICENSE README RELEASE_NOTES TODO \
 ${PKG}/usr/doc/xdg-utils-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/xdg-utils-${V}-${ARCH}-${B}.tlz

