#!/bin/bash
#  Copyright (C) 2010  Matías A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=017
ARCH=${ARCH:-i486}
B=2

PKG=${TMP}/package-pcmciautils

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/pcmciautils-${V}
lzip -cd ${CWD}/pcmciautils-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/pcmciautils-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

# Fix the manpage path:
zcat ${CWD}/Makefile.diff.gz | patch -p0

make
make install DESTDIR=$PKG

strip -s ${PKG}/sbin/pccardctl
chmod 750 ${PKG}/sbin/pccardctl

# Handle config file:
mv $PKG/etc/pcmcia/config.opts{,.new}

# Add init script for PCMCIA devices:
mkdir -p ${PKG}/etc/rc.d
zcat ${CWD}/rc.pcmcia.gz > ${PKG}/etc/rc.d/rc.pcmcia.new
chmod 755 ${PKG}/etc/rc.d/rc.pcmcia.new

# Compress and link manpages:
( cd ${PKG}/usr/man
  find . -type f -exec gzip -9N '{}' +
  find . -type l | while read file ; do
    ln -sf $(readlink $file).gz ${file}.gz
    rm $file
  done
)

# Add the documentation:
mkdir -p ${PKG}/usr/doc/pcmciautils-${V}
cp -a COPYING ${PKG}/usr/doc/pcmciautils-${V}

# Add post-install script:
mkdir -p ${PKG}/install
zcat ${CWD}/post-install.gz > ${PKG}/install/post-install

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/pcmciautils-${V}-${ARCH}-${B}.tlz

