#! /bin/sh
#
# To handle ACPI events.
#

IFS=${IFS}/
set $@

case "$1" in
  button)
    case "$2" in
      power)
        /sbin/init 0
      ;;
      *)
        logger "ACPI action $2 is not defined"
      ;;
    esac
    ;;
  *)
    logger "ACPI group $1 is not defined"
    ;;
esac

