#!/bin/bash
#  Copyright (C) 2011  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

P=gtk-gnutella
V=${V:-0.97}
ARCH=${ARCH:-x86_64}
B=${B:-1}

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-mtune=generic}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j6}

PKG=${TMP}/package-${P}

rm -rf $PKG
mkdir -p $PKG $OUT

rm -rf ${TMP}/${P}-${V}
echo "Uncompressing the tarball..."
tar -xvf ${CWD}/${P}-${V}.tar.lz -C $TMP

cd ${TMP}/${P}-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \
 \) -exec chmod 755 {} + \
 -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \
 \) -exec chmod 644 {} +

CC=gcc \
CFLAGS="$DCFLAGS" \
./build.sh \
 --prefix=/usr \
 --libdir=/usr/lib64 \
 --mandir=/usr/man \
 --gtk2 \
 --configure-only

make $JOBS || make;
make install INSTALL_PREFIX=$PKG

# Install extra icon files:
install -m 644 extra_files/gtk-gnutella.16.png -D \
 ${PKG}/usr/share/icons/hicolor/16x16/apps/gtk-gnutella.png
install -m 644 extra_files/gtk-gnutella.32.png -D \
 ${PKG}/usr/share/icons/hicolor/32x32/apps/gtk-gnutella.png
install -m 644 extra_files/gtk-gnutella.png -D \
 ${PKG}/usr/share/icons/hicolor/48x48/apps/gtk-gnutella.png
install -m 644 extra_files/gtk-gnutella.svg -D \
 ${PKG}/usr/share/icons/hicolor/scalable/apps/gtk-gnutella.svg

# Compress and link .man page(s)?:
if [[ -d ${PKG}/usr/man ]]; then
  ( cd ${PKG}/usr/man
    find . -type f -exec gzip -9N '{}' +
    find . -type l | while read file ; do
      ln -sf $(readlink $file).gz ${file}.gz
      rm $file
    done
  )
fi

# Copy the documentation:
mkdir -p ${PKG}/usr/doc/${P}-${V}
cp -a \
 AUTHORS ChangeLog *LICENSE* README TODO \
 ${PKG}/usr/doc/${P}-${V}

cd $PKG

# Strip binaries & libraries:
find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
 cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || :

# Copy the description files:
mkdir -p description install
cp ${CWD}/description/?? description/
zcat ${CWD}/post-install.gz > install/post-install

# Build the package:
makepkg -l ${OUT}/${P}-${V}-${ARCH}-${B}.tlz

