#!/bin/bash
#  Copyright (C) 2009-2010  Matias A. Fonzo, <selk@dragora.org>
#  Copyright (C) 2012  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=1.4
ARCH=${ARCH:-i486}
B=2

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -march=i486 -mtune=i686}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j4}

PKG=${TMP}/package-gzip

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/gzip-${V}
tar xvf ${CWD}/gzip-${V}.tar.lz -C $TMP

cd ${TMP}/gzip-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

# Gzip was built with autoconf v2.64, so:
#autoreconf --install --force --verbose

CFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --bindir=/bin \
 --infodir=/usr/info \
 --mandir=/usr/man \
 --program-transform-name='s/^z/gz/' \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS
if [[ -n $CHECK ]]; then
  make check;
fi
make install DESTDIR=$PKG

# Without hard links:
( cd ${PKG}/bin
  rm -f uncompress
  ln -s gunzip uncompress
)

# Strip binaries & libraries (if any):
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

# Compress manuals (.info documents and man-pages):
( cd ${PKG}/usr ; rm -f info/dir ; gzip -9Nf info/* man/man?/* )

# No, we don't want hard links!:
( cd ${PKG}/usr/man/man1
  rm -f gunzip.1.gz
  ln -s gzip.1.gz gunzip.1.gz
  rm -f gzcat.1.gz
  ln -s gzip.1.gz gzcat.1.gz
  rm -f gzcmp.1.gz
  ln -s gzdiff.1.gz gzcmp.1.gz
)

# Add the documentation:
mkdir -p ${PKG}/usr/doc/gzip-${V}
cp -a \
 AUTHORS COPYING ChangeLog NEWS README* TODO THANKS \
 ${PKG}/usr/doc/gzip-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/gzip-${V}-${ARCH}-${B}.tlz

