#!/bin/bash
#  Copyright (C) 2009-2011  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=2.1.1
ARCH=${ARCH:-i486}
B=5

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -march=i486 -mtune=i686}

PKG=${TMP}/package-runit

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/runit-${V}
tar -xvf ${CWD}/runit-${V}.tar.lz -C $TMP

mv ${TMP}/admin/runit-${V} $TMP
rmdir ${TMP}/admin

cd ${TMP}/runit-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

# Pick up DCFLAGS:
sed -i "s|gcc -O2|gcc $DCFLAGS|" src/conf-cc

./package/compile

# Install programs:
( cd command
  mkdir -p ${PKG}/{sbin,bin}

  for file in runit* runsv* utmpset ; do
    cp -a $file ${PKG}/sbin
  done

  for file in sv* chpst ; do
    cp -a $file ${PKG}/bin
  done
)

# Install shutdown wrapper:
zcat ${CWD}/shutdown.gz > ${PKG}/sbin/shutdown
( cd ${PKG}/sbin
  ln -s shutdown reboot
  ln -s shutdown poweroff
  ln -s shutdown halt
)

find ${PKG}/sbin -type f | xargs chmod -v 0750

# Make symlink compatibility with 'init':
( cd ${PKG}/sbin
  ln -s runit-init init
)

mkdir -p ${PKG}/var/state/runit

# Strip binaries & libraries (if any):
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

# Install man-pages:
mkdir -p ${PKG}/usr/man/man8
for file in man/* ; do
  gzip -9Nc $file > ${PKG}/usr/man/man8/${file##*/}.gz
done

# Add the documentation:
mkdir -p ${PKG}/usr/doc/runit-${V}/html
cp -a \
 package/{CHANGES,COPYING,README,THANKS,TODO} \
 ${PKG}/usr/doc/runit-${V}
cp -a \
 doc/*.html \
 ${PKG}/usr/doc/runit-${V}/html

# Set sane ownerships:
chown -R 0:0 ${PKG}/

# Add the post-install script:
mkdir -p ${PKG}/install
cat << EOF > ${PKG}/install/post-install
# Reload the init process num. 1:
if [ -x /bin/kill ]; then
  /bin/kill -HUP 1
fi

EOF

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/?? ${PKG}/description

cd $PKG
makepkg -l prepend ${OUT}/runit-${V}-${ARCH}-${B}.tlz

