#!/bin/bash
#  Copyright (C) 2010  Matías A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=2.11
ARCH=${ARCH:-i486}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -march=i486 -mtune=i686}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j3}

PKG=${TMP}/package-cpio

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/cpio-${V}
tar xvf ${CWD}/cpio-${V}.tar.lz -C $TMP

cd ${TMP}/cpio-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

CFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --infodir=/usr/info \
 --mandir=/usr/man \
 --disable-mt \
 --with-rmt=/usr/sbin/rmt \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS
make install DESTDIR=$PKG

strip -s ${PKG}/usr/bin/cpio

# Removes this files:
rm -f \
 ${PKG}/usr/man/man1/mt.1 \
 ${PKG}/usr/info/dir # Redundancy
rmdir ${PKG}/usr/libexec

# Compress cpio man-page and info document:
gzip -9N \
 ${PKG}/usr/man/man1/cpio.1 \
 ${PKG}/usr/info/cpio.info

# Add the documentation:
mkdir -p ${PKG}/usr/doc/cpio-${V}
cp -a \
 AUTHORS COPYING ChangeLog NEWS README THANKS TODO \
 ${PKG}/usr/doc/cpio-${V}

# Copy the description files:
mkdir -p ${PKG}/{description,install}
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/cpio-${V}-${ARCH}-${B}.tlz

