#!/bin/bash
#  Copyright (C) 2007-2011  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=2.0
ARCH=${ARCH:-32b}
B=1

PKG=${TMP}/package-hierarchyfs

rm -rf $PKG
mkdir -p $PKG $OUT

( cd $PKG
  umask 000
  lzip -cd ${CWD}/_hierarchyfs.tar.lz | tar -xf -
)

cd $PKG

cat ${CWD}/dragora-version > etc/dragora-version
cat ${CWD}/README.media > media/README
cat ${CWD}/README.mnt > mnt/README

mkdir -p description
for file in ${CWD}/description/* ; do
  if [[ -f $file ]]; then
    cat $file > description/${file##*/}
  fi
done

mkdir -p install
zcat ${CWD}/post-install-${ARCH}.gz > install/post-install

makepkg ${OUT}/_hierarchyfs-${V}-${ARCH}-${B}.tlz

