#!/bin/bash
#  Copyright (C) 2010-2012  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=3.1.9
ARCH=${ARCH:-x86_64}
B=1

PKG=${TMP}/package-pciutils

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/pciutils-${V}
tar -xvf ${CWD}/pciutils-${V}.tar.lz -C $TMP

cd ${TMP}/pciutils-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

# Get the last "pci.ids":
sh update-pciids.sh

make PREFIX=/usr MANDIR=/usr/man ZLIB=no
make PREFIX=/usr MANDIR=/usr/man install DESTDIR=$PKG

mkdir -p ${PKG}/usr/lib64
install -v -m 644 lib/libpci.a ${PKG}/usr/lib64
strip -g ${PKG}/usr/lib64/libpci.a

mkdir -p ${PKG}/usr/include/pci
install -v -m 644 lib/*.h ${PKG}/usr/include/pci

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

# Increments a little the security:
chmod -v 750 ${PKG}/usr/sbin/*
chmod -v 755 ${PKG}/usr/sbin/lspci

# Compress man-pages:
gzip -9N ${PKG}/usr/man/man?/*.?

# Add the documentation:
mkdir -p ${PKG}/usr/doc/pciutils-${V}
cp -a \
 ChangeLog README TODO pciutils.lsm \
 ${PKG}/usr/doc/pciutils-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/?? ${PKG}/description

cd $PKG
makepkg -l ${OUT}/pciutils-${V}-${ARCH}-${B}.tlz

