#!/bin/bash
# Copyright (C) 2010-2012  Matias A. Fonzo, <selk@dragora.org>
# Copyright (C) 2013-2014  Lucas Sköldqvist <frusen@dragora.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=7.38.0
ARCH=${ARCH:-x86_64}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -mtune=generic}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j4}

PKG=${TMP}/package-curl

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/curl-${V}
lzip -cd ${CWD}/curl-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/curl-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

CFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --libdir=/usr/lib64 \
 --mandir=/usr/man \
 --localstatedir=/var \
 --disable-static \
 --enable-shared \
 --enable-threaded-resolver \
 --without-gnutls \
 --with-ca-path=/etc/ssl/certs \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS
make install DESTDIR=$PKG

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

# Compress and link manpages:
( cd $PKG/usr/man
  find . -type f -exec gzip -9N '{}' +
  find . -type l | while read file ; do
    ln -sf $(readlink $file).gz ${file}.gz
    rm $file
  done
)

# Add the documentation:
mkdir -p ${PKG}/usr/doc/curl-${V}/docs
cp -a \
 CHANGES COPYING README RELEASE-NOTES \
 ${PKG}/usr/doc/curl-${V}
( cd docs
  cp -a \
   BINDINGS BUGS CONTRIBUTE FAQ FEATURES HISTORY \
   INTERNALS KNOWN_BUGS LICENSE-MIXING MANUAL \
   RESOURCES SSLCERTS THANKS TODO VERSIONS \
   ${PKG}/usr/doc/curl-${V}/docs
)

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/curl-${V}-${ARCH}-${B}.tlz
