#!/bin/bash
#  Copyright (C) 2009-2012  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=3.2
ARCH=${ARCH:-i486}
B=2

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -march=i486 -mtune=i686}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j4}

PKG=${TMP}/package-diffutils

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/diffutils-${V}
lzip -cd ${CWD}/diffutils-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/diffutils-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

# The above patch will cause the Diffutils build system to attempt to
# rebuild the diff.1 man page using the unavailable program help2man.
# The result is an unreadable man page for diff. We can avoid this by
# updating the timestamp on the file man/diff.1: 
touch man/diff.1

CFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --infodir=/usr/info \
 --mandir=/usr/man \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS
make install DESTDIR=$PKG

find ${PKG}/usr/bin -type f -exec strip --strip-unneeded '{}' +

# Compress manuals (.info documents and man-pages):
( cd ${PKG}/usr ; rm -f info/dir ; gzip -9N info/* man/man?/* )

# Add the documentation:
mkdir -p ${PKG}/usr/doc/diffutils-${V}
cp -a \
 ABOUT-NLS AUTHORS COPYING ChangeLog NEWS README THANKS \
 ${PKG}/usr/doc/diffutils-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg ${OUT}/diffutils-${V}-${ARCH}-${B}.tlz

