#!/bin/bash
#  Copyright (C) 2009-2010  Matias A. Fonzo, <selk@dragora.org>
#  Copyright (C) 2011-2012  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=4.2
ARCH=${ARCH:-i486}
B=7

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -march=i486 -mtune=i686}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j4}

PKG=${TMP}/package-bash

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/bash-${V}
lzip -cd ${CWD}/bash-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/bash-${V}

# Apply official patches:
for patch in ${CWD}/patches/*-??? ; do
  if [[ -f $patch ]]; then
    patch -p0 < $patch --verbose
  fi
done

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

# http://lists.gnu.org/archive/html/bug-bash/2011-12/msg00079.html
zcat ${CWD}/direxpand.patch.gz | patch -p0 --verbose

CFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --bindir=/bin \
 --infodir=/usr/info \
 --mandir=/usr/man \
 --htmldir=/usr/doc/bash-${V} \
 --enable-multibyte \
 --with-installed-readline \
 --with-curses \
 --without-bash-malloc \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS
make install DESTDIR=$PKG # Yeah!

strip --strip-unneeded ${PKG}/bin/bash

# Make symlink compatibility:
( cd ${PKG}/bin ; ln -sf bash sh )

# Compress manuals:
( cd $PKG
  ( cd usr/info ; rm -f dir ; gzip -9N * )
  ( cd usr/man ; gzip -9N man?/* )
)

# Add the documentation:
mkdir -p ${PKG}/usr/doc/bash-${V}
cp -a \
 ABOUT-NLS AUTHORS CHANGES COMPAT COPYING \
 NEWS NOTES POSIX RBASH README Y2K doc/{FAQ,INTRO} \
 ${PKG}/usr/doc/bash-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/bash-${V}-${ARCH}-${B}.tlz

