#!/bin/bash
#  Copyright (C) 2010  Matías A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=0.998
ARCH=${ARCH:-x86_64}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -mtune=generic}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j5}

PKG=${TMP}/package-xsane

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/xsane-${V}
lzip -cd ${CWD}/xsane-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/xsane-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

zcat ${CWD}/patches/fixdocdir.diff.gz | patch -p0 --verbose
zcat ${CWD}/patches/xsane.h.defbrowser.diff.gz | patch -p0 --verbose

CFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --sysconfdir=/etc \
 --mandir=/usr/man \
 --localstatedir=/var \
 --disable-static \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS xsanedocdir=/usr/doc/xsane-${V}
make install xsanedocdir=/usr/doc/xsane-${V} DESTDIR=$PKG

strip --strip-unneeded ${PKG}/usr/bin/xsane
gzip -9N ${PKG}/usr/man/man1/xsane.1

# Purge package:
find $PKG -type d -empty -delete -print

# Copy the rest of the documentation:
cp -a \
 ICM.TODO xsane.ACCELKEYS xsane.AUTHOR xsane.BEGINNERS-INFO xsane.BUGS \
 xsane.CHANGES xsane.COPYING xsane.FAQ xsane.LANGUAGES xsane.LOGO \
 xsane.NEWS xsane.ONLINEHELP xsane.PROBLEMS xsane.REMOVE xsane.ROOT \
 xsane.TODO xsane.VENDOR-STRINGS \
 ${PKG}/usr/doc/xsane-${V}

# Add the post-install script and the description files:
mkdir -p ${PKG}/{install,description}
zcat ${CWD}/post-install.gz > ${PKG}/install/post-install
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/xsane-${V}-${ARCH}-${B}.tlz

