#!/bin/bash
#  Copyright (C) 2010-2012  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=rev1499
ARCH=${ARCH:-x86_64}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -mtune=generic}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j4}

PKG=${TMP}/package-xchat

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/xchat-${V}
lzip -cd ${CWD}/xchat-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/xchat-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

# Apply a diff to handle URLs with GNU IceCat:
zcat ${CWD}/url-handler.diff.gz | patch -p0 --verbose

chmod 755 ./autogen.sh
./autogen.sh

CFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --libdir=/usr/lib64 \
 --sysconfdir=/etc \
 --disable-static \
 --localstatedir=/var \
 --enable-mmx \
 --enable-shm \
 --enable-spell=libsexy \
 --enable-openssl \
 --enable-socks \
 --enable-ipv6 \
 --enable-dbus \
 --enable-tcl=/usr/lib64 \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS
make install DESTDIR=$PKG

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

# Add the documentation:
mkdir -p ${PKG}/usr/doc/xchat-${V}
cp -a \
 AUTHORS COPYING ChangeLog HACKING README \
 ${PKG}/usr/doc/xchat-${V}

# Make the post-install script:
mkdir -p ${PKG}/install
cat << "EOF" > ${PKG}/install/post-install
if [ -x /usr/bin/update-desktop-database ]; then
  /usr/bin/update-desktop-database -q ./usr/share/applications
fi

EOF

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/xchat-${V}-${ARCH}-${B}.tlz

