#!/bin/bash
#  Copyright (C) 2010-2011  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=2.41
ARCH=${ARCH:-x86_64}
B=2

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j2}

PKG=${TMP}/package-XML-Parser

PKG=${PKG}/pkg/XML-Parser/${V}

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
cd $TMP

rm -rf xml-parser-${V}
lzip -cd ${CWD}/XML-Parser-${V}.tar.lz | tar -xvf - -C $TMP

mv XML-Parser-${V} xml-parser-${V}

cd xml-parser-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

perl Makefile.PL
make $JOBS
make install DESTDIR=$PKG

# Remove the temporary directory from the inventory file of Perl:
perlVersion=$(eval $(perl -V:version); printf "$version")

find ${PKG}/usr -type f -name '.packlist' -exec \
 sed -i "s#$PKG##g" '{}' +

find ${PKG}/usr -type f -name 'perllocal.pod' -delete

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

gzip -9N ${PKG}/usr/man/man?/*.?

# Add the documentation:
mkdir -p ${PKG}/usr/doc/xml-parser-${V}
cp -a \
 Changes README \
 ${PKG}/usr/doc/xml-parser-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/xml-parser-${V}-${ARCH}-${B}.tlz

