#!/bin/bash
#  Copyright (C) 2009-2012  Matias A. Fonzo, <selk@dragora.org>
#  Copyright (C) 2014  Matias A. Fonzo, <selk@dragora.org>
#  Copyright (C) 2015  Lucas Sköldqvist, <frusen@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=1.0.0r
ARCH=${ARCH:-i486}
B=1

PKG=${TMP}/package-openssl

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/openssl-${V}
lzip -cd ${CWD}/openssl-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/openssl-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

./config \
 --prefix=/usr \
 --openssldir=/etc/ssl \
 no-sse2 \
 enable-md2 \
 shared \
 zlib-dynamic

make depend
make
make INSTALL_PREFIX=$PKG MANDIR=/usr/man install

# Fix library permissions:
for dir in usr/lib usr/lib/engines ; do
  ( cd ${PKG}/$dir ; find . -type f -name '*.so*' | xargs chmod 755 )
  ( cd ${PKG}/$dir ; ldconfig -l * 2> /dev/null )
done

# Handle config file:
mv ${PKG}/etc/ssl/openssl.cnf{,.new}

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
  find . -type f | xargs file | awk '/current ar archive/' | \
   cut -f 1 -d : | xargs strip --strip-debug 2> /dev/null
)

# Backward-compatibility symlink to SSLeay:
( cd ${PKG}/usr/bin ; ln -sf openssl ssleay )

# Copy the non-fucking-commercial certificates:
mkdir -p ${PKG}/etc/ssl/certs
cp -a certs/* ${PKG}/etc/ssl/certs

# Compress and link manpages:
( cd ${PKG}/usr/man
  find . -type f -exec gzip -9N '{}' +
  find . -type l | while read file ; do
    ln -sf $(readlink $file).gz ${file}.gz
    rm $file
  done
)

# Add the documentation:
mkdir -p ${PKG}/usr/doc/openssl-${V}
cp -a \
 CHANGES* FAQ LICENSE NEWS PROBLEMS README \
 ${PKG}/usr/doc/openssl-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/?? ${PKG}/description

# Add post-install script:
mkdir -p ${PKG}/install
zcat ${CWD}/post-install.gz > ${PKG}/install/post-install

cd $PKG
makepkg -l ${OUT}/openssl-${V}-${ARCH}-${B}.tlz

