#!/bin/bash
#  Copyright (C) 2010-2011  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

P=polipo
V=${V:-1.0.4.1}
ARCH=${ARCH:-x86_64}
B=${B:-1}

PKG=${TMP}/package-${P}

rm -rf $PKG
mkdir -p $PKG $OUT

rm -rf ${TMP}/${P}-${V}
echo "Uncompressing the tarball..."
tar -xvf ${CWD}/${P}-${V}.tar.lz -C $TMP

cd ${TMP}/${P}-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \
 \) -exec chmod 755 {} + \
 -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \
 \) -exec chmod 644 {} +

make PREFIX=/usr CDEBUGFLAGS="-O2 -fPIC -Wall"
make PREFIX=/usr install TARGET=$PKG

mkdir -p ${PKG}/etc/polipo
mkdir -p ${PKG}/var/cache/polipo

# Include the config file:
mkdir -p ${PKG}/etc/polipo
cat ${CWD}/polipo.conf > ${PKG}/etc/polipo/config.new

# Include our "polipo" daemon for runit:
install -m 755 ${CWD}/polipo.runit -D ${PKG}/etc/sv/polipo/run.new
install -d ${PKG}/etc/runit/runsvdir/default
( cd ${PKG}/etc/runit/runsvdir/default
  ln -sf /etc/sv/polipo .
)

# Compress .info page(s):
if [[ -d ${PKG}/usr/info ]]; then
  ( cd ${PKG}/usr/info
    rm -f dir  # Redundancy.
    gzip -9N *.info*
  )
fi

# Compress man page(s):
if [[ -d ${PKG}/usr/man ]]; then
  ( cd ${PKG}/usr/man
    gzip -9N man?/*.?
  )
fi

# Copy the documentation:
mkdir -p ${PKG}/usr/doc/${P}-${V}
cp -a \
 CHANGES COPYING README \
 ${PKG}/usr/doc/${P}-${V}

cd $PKG

# Strip binaries & libraries:
find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
 cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true;

# Copy description files, adding the post install script:
mkdir -p description install
cp ${CWD}/description/?? description/
zcat ${CWD}/post-install.gz > install/post-install

# Build the package:
makepkg -l ${OUT}/${P}-${V}-${ARCH}-${B}.tlz

