#!/bin/bash
#  Copyright (C) 2010-2012  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=0.8.10
ARCH=${ARCH:-i486}
case "$ARCH" in
  i*) PKG_ARCH=i686;;
esac
B=${B:-1}

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -march=i686}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j4}

PKG=${TMP}/package-gnash

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/gnash-${V}
lzip -cd ${CWD}/gnash-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/gnash-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

CFLAGS="$DCFLAGS" \
CXXFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --sysconfdir=/etc/gnash \
 --mandir=/usr/man \
 --docdir=/usr/doc/gnash-${V} \
 --htmldir=/usr/doc/gnash-${V}/html \
 --localstatedir=/var \
 --disable-static \
 --enable-shared \
 --enable-ssl \
 --enable-python \
 --enable-renderer=agg,cairo \
 --enable-gui=gtk \
 --enable-media=gst \
 --enable-device=x11 \
 --with-plugins-install=system \
 --with-npapi-plugindir=/usr/lib/gnash \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS
make install DESTDIR=$PKG
make install-plugins DESTDIR=$PKG

# To handle config:
( cd ${PKG}/etc/gnash
  mv gnashpluginrc{,.new}
  mv gnashrc{,.new}
)

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

# Install the missing .la file:
mkdir -p ${PKG}/usr/lib/gnash
( cd plugin/npapi
  install -m 0755 libgnashplugin.la ${PKG}/usr/lib/gnash
)
# Make plugin symlink for Mozilla:
mkdir -p ${PKG}/usr/lib/plugins/mozilla
( cd ${PKG}/usr/lib/plugins/mozilla
  ln -sf ../../gnash/libgnashplugin.so .
)

# Compress and link manpages (if needed):
( cd ${PKG}/usr/man
  find . -type f -exec gzip -9N '{}' +
  find . -type l | while read file ; do
    ln -sf $(readlink $file).gz ${file}.gz
    rm $file
  done
)

# Copy the documentation:
mkdir -p ${PKG}/usr/doc/gnash-${V}
cp -a \
 ABOUT-NLS AUTHORS COPYING ChangeLog NEWS README TODO \
 ${PKG}/usr/doc/gnash-${V}

# Add the post install script:
mkdir -p ${PKG}/install
zcat ${CWD}/post-install.gz > ${PKG}/install/post-install

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/?? ${PKG}/description

cd $PKG
makepkg -l ${OUT}/gnash-${V}-${PKG_ARCH}-${B}.tlz

