#!/bin/bash
#  Copyright (C) 2009-2011  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=1.1-20111020
ARCH=${ARCH:-i486}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -march=i486 -mtune=i686}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j4}

PKG=${TMP}/package-dialog

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/dialog-${V}
lzip -cd ${CWD}/dialog-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/dialog-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

CFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --bindir=/bin \
 --sysconfdir=/etc \
 --with-ncurses \
 --with-ncursesw \
 --enable-widec \
 --enable-nls \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS
make install DESTDIR=$PKG

strip --strip-unneeded ${PKG}/bin/dialog

# The look & feel from Dragora Ardi System:
mkdir -p ${PKG}/etc
zcat ${CWD}/dialogrc.gz > ${PKG}/etc/dialogrc.new

# Compress the man-pages:
gzip -9N ${PKG}/usr/man/man1/dialog.1
mkdir -p ${PKG}/usr/man/man3
gzip -9Nc < dialog.3 > ${PKG}/usr/man/man3/dialog.3.gz

# Add the documentation:
mkdir -p ${PKG}/usr/doc/dialog-${V}
cp -a \
 CHANGES COPYING README VERSION dialog.lsm \
 ${PKG}/usr/doc/dialog-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

# Write the post-install script:
mkdir -p ${PKG}/install
cat << "EOF" > ${PKG}/install/post-install
# Handle config files:
config() {
  local new old
  new="$1"
  old=${1%.new}
  if [ ! -r $old ]; then
    mv $new $old
  elif [ "$(md5sum $old | cut -f 1 -d ' ')" = "$(md5sum $new | cut -f 1 -d ' ')" ]; then
    rm $new
  else
    echo "You have a new config file \"${ROOT}/${new}\" at your consideration."
  fi
}

config etc/dialogrc.new

EOF

cd $PKG
makepkg -l ${OUT}/dialog-${V}-${ARCH}-${B}.tlz

