#!/bin/bash
#  Copyright (C) 2010  Matías A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=29
ARCH=${ARCH:-i486}
B=1

PKG=${TMP}/package-wireless_tools

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/wireless_tools.${V}
lzip -cd ${CWD}/wireless_tools.${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/wireless_tools.${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

make
make install PREFIX=${PKG}/usr INSTALL_LIB=${PKG}/usr/lib

# Increments the security:
find ${PKG}/usr/sbin -type f | xargs chmod -v 750

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip -s 2> /dev/null
)

# Add manpages:
mkdir -p ${PKG}/usr/man/{cs,fr}/man{8,7,5}
cp -a cs/*.8 $PKG/usr/man/cs/man8
cp -a cs/*.7 $PKG/usr/man/cs/man7
cp -a cs/*.5 $PKG/usr/man/cs/man5
cp -a fr/*.8 $PKG/usr/man/fr/man8
cp -a fr/*.7 $PKG/usr/man/fr/man7
cp -a fr/*.5 $PKG/usr/man/fr/man5

( cd ${PKG}/usr/man
  find . -type f | xargs chmod 644            # Set permissions.
  find . -type f -name '*.?' | xargs gzip -9  # Compress the pages.
)

# Add the documentation:
mkdir -p ${PKG}/usr/doc/wireless_tools-${V}
cp -a \
 COPYING README* *.txt \
 ${PKG}/usr/doc/wireless_tools-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/wireless_tools-${V}-${ARCH}-${B}.tlz

