#!/bin/bash
#  Copyright (C) 2010-2012  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

P=pidgin
V=${V:-2.10.3}
ARCH=${ARCH:-i486}
B=${B:-2}

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -march=i486 -mtune=i686}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j6}

PKG=${TMP}/package-${P}

rm -rf $PKG
mkdir -p $PKG $OUT

rm -rf ${TMP}/${P}-${V}
echo "Uncompressing the tarball..."
tar -xvf ${CWD}/${P}-${V}.tar.lz -C $TMP

cd ${TMP}/${P}-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

CFLAGS="$DCFLAGS" \
CXXFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --mandir=/usr/man \
 --sysconfdir=/etc \
 --localstatedir=/var \
 --disable-static \
 --disable-debug \
 --enable-perl \
 --enable-gnutls \
 --disable-gtkspell \
 --disable-meanwhile \
 --disable-avahi \
 --disable-nm \
 --enable-shared \
 --enable-nss \
 --enable-vv \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS V=1
make install DESTDIR=$PKG

# Remove the temporary directory from the inventory file of Perl:
perlVersion=$(eval $(perl -V:version); printf "$version")

find ${PKG}/usr -type f -name '.packlist' -exec \
 sed -i "s#$PKG##g" '{}' +

find ${PKG}/usr -type f -name 'perllocal.pod' -delete

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

# Compress man page(s):
gzip -9N ${PKG}/usr/man/man?/*.?

# Add the documentation:
mkdir -p ${PKG}/usr/doc/${P}-${V}
cp -a \
 AUTHORS COPYING COPYRIGHT ChangeLog HACKING NEWS PLUGIN_HOWTO README \
 ${PKG}/usr/doc/${P}-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/?? ${PKG}/description

# Add the post install script:
mkdir -p ${PKG}/install
zcat ${CWD}/post-install.gz > ${PKG}/install/post-install

cd $PKG
makepkg -l ${OUT}/${P}-${V}-${ARCH}-${B}.tlz

