#!/bin/bash
#  Copyright (C) 2010-2011  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=1_7R3
ARCH=${ARCH:-i486}
B=1

PKG=${TMP}/package-rhino

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
cd $TMP
rm -rf rhino${V}
lzip -cd ${CWD}/rhino${V}.tar.lz | tar -xvf -

cd rhino${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

install -d ${PKG}/usr/share/java
cat js.jar > ${PKG}/usr/share/java/js.jar

# Install the documentation:
install -d ${PKG}/usr/doc/rhino-${V}/html
cp -a javadoc/* ${PKG}/usr/doc/rhino-${V}/html
cp -a LICENSE.txt ${PKG}/usr/doc/rhino-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/rhino-${V}-${ARCH}-${B}.tlz

