#!/bin/bash
#  Copyright (C) 2009-2011  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=20100910
ARCH=${ARCH:-i486}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -march=i486 -mtune=i686}

PKG=${TMP}/package-sysklogd

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/sysklogd-${V}
tar xvf ${CWD}/sysklogd-${V}.tar.lz -C $TMP

cd ${TMP}/sysklogd-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

# Changes the location of the binaries (under sbin directory):
sed -i \
 -e s#'BINDIR = $(prefix)/usr/sbin'#'BINDIR = $(prefix)/sbin'# Makefile

# Changes the location of the man-pages (under usr/man directory):
sed -i \
 -e s#'MANDIR = $(prefix)/usr/share/man'#'MANDIR = $(prefix)/usr/man'# Makefile

# Let's go:
export CFLAGS="$DCFLAGS"
make
mkdir -p ${PKG}/sbin
mkdir -p ${PKG}/usr/man/man{5,8}
make prefix=$PKG install

strip --strip-unneeded ${PKG}/sbin/*
find ${PKG}/sbin -type f | xargs chmod -v 750

# Add our custom config file:
mkdir -p ${PKG}/etc
cat ${CWD}/config/syslog.conf > ${PKG}/etc/syslog.conf.new
chmod 640 ${PKG}/etc/syslog.conf.new
mkdir -p ${PKG}/etc/runit/runsvdir/default
for daemon in klogd syslogd ; do
  mkdir -p ${PKG}/etc/sv/$daemon
  cat ${CWD}/config/$daemon > ${PKG}/etc/sv/${daemon}/run.new
  chmod 755 ${PKG}/etc/sv/${daemon}/run.new
  ( cd ${PKG}/etc/runit/runsvdir/default ; ln -sf /etc/sv/$daemon . )
done

# Add the "logrotate" file:
mkdir -p ${PKG}/etc/logrotate.d
cat ${CWD}/config/syslogd.logrotate > ${PKG}/etc/logrotate.d/syslogd.new

mkdir -p ${PKG}/var/log

# Compress and link man-pages:
gzip -9N ${PKG}/usr/man/man{5,8}/*
( cd ${PKG}/usr/man/man8
  ln -sf sysklogd.8.gz syslogd.8.gz
)

# Add the documentation:
mkdir -p ${PKG}/usr/doc/sysklogd-${V}
cp -a \
 ANNOUNCE CHANGES COPYING MANIFEST NEWS README.1st README.linux \
 ${PKG}/usr/doc/sysklogd-${V}

# Copy the description files:
mkdir -p ${PKG}/{description,install}
cp ${CWD}/description/* ${PKG}/description
# Add post-install script:
zcat ${CWD}/post-install.gz > ${PKG}/install/post-install

cd $PKG
makepkg -l ${OUT}/sysklogd-${V}-${ARCH}-${B}.tlz

