#!/bin/bash
#  Copyright (C) 2010-2011  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=0.9.23
ARCH=${ARCH:-i486}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -march=i486 -mtune=i686}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j4}

PKG=${TMP}/package-pulseaudio

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/pulseaudio-${V}
lzip -cd ${CWD}/pulseaudio-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/pulseaudio-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

# Apply custom configuration:
zcat ${CWD}/files/default.pa.diff | patch -p0 --verbose

CFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --sysconfdir=/etc \
 --mandir=/usr/man \
 --localstatedir=/var \
 --disable-static \
 --enable-hal \
 --disable-hal-compat \
 --disable-legacy-runtime-dir \
 --with-database=simple \
 --with-system-user=pulse \
 --with-system-group=pulse \
 --with-access-group=pulse-access \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS
make install DESTDIR=$PKG

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

# Add configuration for ALSA:
zcat ${CWD}/files/asound.conf.gz > ${PKG}/etc/asound.conf.new

# Install the daemon for runit:
install -m 755 ${CWD}/pulseaudio.runit \
 -D ${PKG}/etc/sv/pulseaudio/run.new
( mkdir -p ${PKG}/etc/runit/runsvdir/default
  cd ${PKG}/etc/runit/runsvdir/default
  ln -sf /etc/sv/pulseaudio .
)

# Install state directories:
install -d -o pulse -g pulse ${PKG}/var/lib/pulse
install -d -o pulse -g pulse ${PKG}/var/run/pulse

# Changes the number of the rule:
mv ${PKG}/lib/udev/rules.d/90-pulseaudio.rules \
 ${PKG}/lib/udev/rules.d/92-pulseaudio.rules

# To handle config:
( cd ${PKG}/etc
  mv pulse/client.conf{,.new}
  mv pulse/daemon.conf{,.new}
  mv dbus-1/system.d/pulseaudio-system.conf{,.new}
)

# Compress and link manpages:
( cd ${PKG}/usr/man
  find . -type f -exec gzip -9N '{}' +
  find . -type l | while read file ; do
    ln -sf $(readlink $file).gz ${file}.gz
    rm $file
  done
)

# Add the documentation:
mkdir -p ${PKG}/usr/doc/pulseaudio-${V}
cp -a \
 ABOUT-NLS *GPL* LICENSE README \
 ${PKG}/usr/doc/pulseaudio-${V}

# Add the post-install script:
mkdir -p ${PKG}/install
zcat ${CWD}/post-install.gz > ${PKG}/install/post-install

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/pulseaudio-${V}-${ARCH}-${B}.tlz

