#!/bin/bash
#  Copyright (C) 2009-2011  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=4.5
ARCH=${ARCH:-i486}
B=1

PKG=${TMP}/package-dcron

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."

cd $TMP

rm -rf dcron-${V}
tar xvf ${CWD}/dcron-${V}.tar.lz

cd dcron-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

# Build source:
make PREFIX=/usr MANDIR=/usr/man
mkdir -p ${PKG}/usr/{bin,sbin}
mkdir -p ${PKG}/usr/man/man{1,8}
make install DESTDIR=$PKG

# Create empty directories:
mkdir -p ${PKG}/etc/cron.d
mkdir -p ${PKG}/etc/cron.{daily,hourly,monthly,weekly}
mkdir -p ${PKG}/var/spool/cron/crontabs

# Set ownerships and permissions:
chown 0:wheel ${PKG}/var/spool/cron
chown 0:wheel ${PKG}/var/spool/cron/crontabs
chmod 750 ${PKG}/var/spool/cron
chmod 750 ${PKG}/var/spool/cron/crontabs

# Add custom files:
cat ${CWD}/config/run-parts > ${PKG}/usr/bin/run-parts
chmod 755 ${PKG}/usr/bin/run-parts
cat ${CWD}/config/root-crontab > ${PKG}/var/spool/cron/crontabs/root.new
chmod 600 ${PKG}/var/spool/cron/crontabs/root.new

mkdir -p ${PKG}/etc/sv/crond
cat ${CWD}/config/crond > ${PKG}/etc/sv/crond/run.new
chmod 755 ${PKG}/etc/sv/crond/run.new
mkdir -p ${PKG}/etc/runit/runsvdir/default
( cd ${PKG}/etc/runit/runsvdir/default ; ln -sf /etc/sv/crond . )

# Compress man-pages:
gzip -9N ${PKG}/usr/man/man?/*.?

# Add the documentation:
mkdir -p ${PKG}/usr/doc/dcron-${V}
cp -a \
 CHANGELOG README \
 ${PKG}/usr/doc/dcron-${V}

# Copy the description files:
mkdir -p ${PKG}/{description,install}
cp ${CWD}/description/* ${PKG}/description

# Add post-install script:
zcat ${CWD}/post-install.gz > ${PKG}/install/post-install

cd $PKG
makepkg ${OUT}/dcron-${V}-${ARCH}-${B}.tlz

