#!/bin/bash
#  Copyright (C) 2010-2011  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

P=epdfview
V=${V:-0.1.8}
ARCH=${ARCH:-i486}
B=${B:-2}

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -march=i486 -mtune=i686}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j4}

PKG=${TMP}/package-${P}

rm -rf $PKG
mkdir -p $PKG $OUT

rm -rf ${TMP}/${P}-${V}
echo "Uncompressing the tarball..."
tar -xvf ${CWD}/${P}-${V}.tar.lz -C $TMP

cd ${TMP}/${P}-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \
 \) -exec chmod 755 {} + \
 -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \
 \) -exec chmod 644 {} +

CFLAGS="$DCFLAGS" \
CXXFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --infodir=/usr/info \
 --mandir=/usr/man \
 --with-cups \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS || make;
make install DESTDIR=$PKG

# Compress .info page(s)?:
if [[ -d ${PKG}/usr/info ]]; then
  ( cd ${PKG}/usr/info
    rm -f dir  # Redundancy.
    gzip -9N *.info*
  )
fi

# Compress and link .man page(s)?:
if [[ -d ${PKG}/usr/man ]]; then
  ( cd ${PKG}/usr/man
    find . -type f -exec gzip -9N '{}' +
    find . -type l | while read file ; do
      ln -sf $(readlink $file).gz ${file}.gz
      rm $file
    done
  )
fi

# Copy the documentation:
mkdir -p ${PKG}/usr/doc/${P}-${V}
cp -a \
 AUTHORS COPYING NEWS README THANKS \
 ${PKG}/usr/doc/${P}-${V}

cd $PKG

# Fix entry for the icon:
( cd usr/share/applications
  sed -i \
   's%Icon=icon_epdfview\(.*\)%Icon=/usr/share/epdfview/pixmaps/icon_epdfview-24.png%' \
    epdfview.desktop
)

# Make freedesktop compliant:
mkdir -p usr/share/icons/hicolor/{24x24,32x32,48x48}/apps
( cd usr/share/icons/hicolor
  ( cd 24x24/apps
    ln -sf ../../../../epdfview/pixmaps/icon_epdfview-24.png epdfview.png
  )
  ( cd 32x32/apps
    ln -sf ../../../../epdfview/pixmaps/icon_epdfview-32.png epdfview.png
  )
  ( cd 48x48/apps
    ln -sf ../../../../epdfview/pixmaps/icon_epdfview-48.png epdfview.png
  )
)

# Strip binaries & libraries:
find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
 cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true;

# Copy description files including the post install script:
mkdir -p description install
cp ${CWD}/description/?? description/
zcat ${CWD}/post-install.gz > install/post-install

# Build the package:
makepkg -l ${OUT}/${P}-${V}-${ARCH}-${B}.tlz

