#!/bin/bash
#  Copyright (C) 2010  Matías A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=0.7.4
ARCH=${ARCH:-i486}
B=1

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j4}

PKG=${TMP}/package-a52dec

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/a52dec-${V}
lzip -cd ${CWD}/a52dec-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/a52dec-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

zcat ${CWD}/patches/activate.pic.diff.gz | patch -p0 --verbose
zcat ${CWD}/patches/make.soname.diff.gz | patch -p0 --verbose

./bootstrap

./configure \
 --prefix=/usr \
 --mandir=/usr/man \
 --localstatedir=/var \
 --enable-static \
 --enable-shared \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS
make install DESTDIR=$PKG

# Missing header ?:
install -m 644 liba52/a52_internal.h \
 ${PKG}/usr/include/a52dec/

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)
strip --strip-debug ${PKG}/usr/lib/liba52.a

# Compress manpages ?:
if [[ -d ${PKG}/usr/man ]]; then
  gzip -9N ${PKG}/usr/man/man?/*.?
fi

# Add the documentation:
mkdir -p ${PKG}/usr/doc/a52dec-${V}
cp -a \
 AUTHORS COPYING ChangeLog HISTORY NEWS README TODO doc/liba52.txt \
 ${PKG}/usr/doc/a52dec-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/a52dec-${V}-${ARCH}-${B}.tlz

