#!/bin/bash
#  Copyright (C) 2012  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

P=abiword
V=${V:-2.8.6}
ARCH=${ARCH:-i486}
B=${B:-2}

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -march=i486 -mtune=i686}

PKG=${TMP}/package-${P}

rm -rf $PKG
mkdir -p $PKG $OUT

rm -rf ${TMP}/${P}-${V}
echo "Uncompressing the tarball..."
tar -xvf ${CWD}/${P}-${V}.tar.lz -C $TMP

cd ${TMP}/${P}-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \
 \) -exec chmod 755 {} + \
 -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \
 \) -exec chmod 644 {} +

# A patch to compile against Boost Asio:
zcat ${CWD}/patches/boost_asio.patch.gz | patch -p1 --verbose

zcat ${CWD}/patches/abiword-2.8.6-glib-header-fix.patch.gz | \
 patch -p1 --verbose

autoreconf -f -i

CFLAGS="$DCFLAGS" \
CXXFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --sysconfdir=/etc \
 --localstatedir=/var \
 --infodir=/usr/info \
 --mandir=/usr/man \
 --disable-static \
 --enable-dynamic \
 --enable-plugins \
 --enable-clipart \
 --enable-templates \
 --program-prefix= \
 --program-suffix= \
 --build=${ARCH}-dragora-linux-gnu

make
make install DESTDIR=$PKG

# Install the documentation:
tar xf ${CWD}/abiword-docs-${V}.tar.lz
( cd abiword-docs-${V}
  export PATH=${PKG}/usr/bin:${PATH}
  export PKG_CONFIG_PATH=${PKG}/usr/lib/pkgconfig:${PKG_CONFIG_PATH}
  ./configure \
   --prefix=/usr \
   --docdir=/usr/doc/abiword-${V} \
   --build=${ARCH}-dragora-linux-gnu

  LD_LIBRARY_PATH=${PKG}/usr/lib:${LD_LIBRARY_PATH} \
  make && make install DESTDIR=$PKG
)

# Move the icon directory:
mv ${PKG}/usr/share/icons ${PKG}/usr/share/pixmaps

# Compress .info page(s)?:
if [[ -d ${PKG}/usr/info ]]; then
  ( cd ${PKG}/usr/info
    rm -f dir  # Redundancy.
    gzip -9N *.info*
  )
fi

# Compress and link .man page(s)?:
if [[ -d ${PKG}/usr/man ]]; then
  ( cd ${PKG}/usr/man
    find . -type f -exec gzip -9N '{}' +
    find . -type l | while read file ; do
      ln -sf $(readlink $file).gz ${file}.gz
      rm $file
    done
  )
fi

# Copy the documentation:
mkdir -p ${PKG}/usr/doc/${P}-${V}
cp -a \
 AUTHORS COPYING COPYRIGHT.TXT ChangeLog NEWS README \
 ${PKG}/usr/doc/${P}-${V}

cd $PKG

# Strip binaries & libraries:
find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
 cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || :

# Copy the description files:
mkdir -p description install
cp ${CWD}/description/?? description/
zcat ${CWD}/post-install.gz > install/post-install

# Build the package:
makepkg -l ${OUT}/${P}-${V}-${ARCH}-${B}.tlz

