#!/bin/bash
#  Copyright (C) 2010-2012  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=3.2.0
ARCH=${ARCH:-x86_64}
B=2

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j4}

PKG=${TMP}/package-iproute2

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/iproute2-${V}
lzip -cd ${CWD}/iproute2-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/iproute2-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

# Fix path:
sed -i \
 -e s"%LIBDIR=/usr/lib%LIBDIR=/usr/lib64%" \
 -e s"%DOCDIR=/share/doc/iproute2%DOCDIR=/usr/doc/iproute2-${V}%" \
 -e s'%MANDIR=/share/man%MANDIR=/usr/man%' \
  Makefile

# Fix up path to iptables:
sed -i s'|/usr/local/lib/iptables|/usr/lib64/iptables|' \
 include/iptables.h

make $JOBS
make install DESTDIR=$PKG

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

mkdir -p ${PKG}/var/lib/arpd

# Increments a little the security:
( cd $PKG
  find sbin -type f | xargs chmod -v 0750
)

# Handle config files:
for f in ${PKG}/etc/iproute2/*; do mv $f ${f}.new ; done

# Add our loopback device script:
mkdir -p ${PKG}/etc/rc.d
zcat ${CWD}/rc.iface_lo.gz > ${PKG}/etc/rc.d/rc.iface_lo.new
chmod 755 ${PKG}/etc/rc.d/rc.iface_lo.new

# Compress and link manpages:
( cd $PKG/usr/man
  find . -type f -exec gzip -9N '{}' +
  find . -type l | while read file ; do
    ln -sf $(readlink $file).gz ${file}.gz
    rm $file
  done
)

# Add the documentation:
mkdir -p ${PKG}/usr/doc/iproute2-${V}
cp -a \
 COPYING README* \
 ${PKG}/usr/doc/iproute2-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

# Add the post-install script:
mkdir -p ${PKG}/install
zcat ${CWD}/post-install.gz > ${PKG}/install/post-install

cd $PKG
makepkg -l ${OUT}/iproute2-${V}-${ARCH}-${B}.tlz

