#!/bin/bash
#  Copyright (C) 2009-2012  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=8.16
ARCH=${ARCH:-i486}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -march=i486 -mtune=i686}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j4}

PKG=${TMP}/package-coreutils

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/coreutils-${V}
lzip -cd ${CWD}/coreutils-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/coreutils-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \
 \) -exec chmod 755 {} + \
 -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \
 \) -exec chmod 644 {} +

# Display correctly the processor type on `uname -p':
zcat ${CWD}/patches/coreutils-8.11-uname-1.patch.gz | patch -p1 --verbose

FORCE_UNSAFE_CONFIGURE=1 \
DEFAULT_POSIX2_VERSION=200112 \
CFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --sysconfdir=/etc \
 --infodir=/usr/info \
 --mandir=/usr/man \
 --enable-no-install-program=arch,hostname,kill,uptime,su \
 --with-tty-group \
 --without-gmp \
 --with-packager="Matias A. Fonzo" \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS
make install DESTDIR=$PKG

# Strip binaries & libraries (if any):
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

# Add "DIR_COLORS" file:
mkdir -p ${PKG}/etc/profile.d
cat src/dircolors.hin > ${PKG}/etc/DIR_COLORS

zcat ${CWD}/profile.d/dircolors.gz > ${PKG}/etc/profile.d/dircolors.new
chmod 755 ${PKG}/etc/profile.d/dircolors.new

# Creates the link to "ginstall", since many sources use it to install:
( cd ${PKG}/usr/bin ; ln -sf install ginstall )

# It seems that this location is wrong.  Otherwise, let me know:
find ${PKG}/usr/share/locale -type d -name 'LC_TIME' | xargs rm -rf

# Compress GNU info documents:
( cd ${PKG}/usr/info ; rm -f dir ; gzip -9N * )

# Compress and link man pages:
( cd ${PKG}/usr/man
  find . -type f -exec gzip -9 '{}' +
  find . -type l | while read file ; do
    ln -sf $(readlink $file).gz ${file}.gz
    rm $file
  done
)

# Copy documentation:
mkdir -p ${PKG}/usr/doc/coreutils-${V}
cp -a \
 ABOUT-NLS AUTHORS COPYING ChangeLog NEWS \
 README THANKS THANKS-to-translators TODO \
 ${PKG}/usr/doc/coreutils-${V}

# Copy the description files:
mkdir -p ${PKG}/{description,install}
cp ${CWD}/description/* ${PKG}/description

# Add post-install script:
zcat ${CWD}/post-install.gz > ${PKG}/install/post-install

cd $PKG
makepkg -l ${OUT}/coreutils-${V}-${ARCH}-${B}.tlz

