#!/bin/bash
#  Copyright (C) 2010  Matías A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=12.5
ARCH=${ARCH:-x86_64}
B=1

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j4}

PKG=${TMP}/package-mailx

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/mailx-${V}
tar xvf ${CWD}/mailx-${V}.tar.lz -C $TMP

cd ${TMP}/mailx-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

# Custom configuration:
zcat ${CWD}/Makefile.diff.gz | patch -p0 --verbose || exit 1;

make $JOBS
make install DESTDIR=$PKG

strip -s ${PKG}/usr/bin/mailx
( cd ${PKG}/usr/bin ; ln -sf mailx mail )

gzip -9N ${PKG}/usr/man/man1/mailx.1
( cd ${PKG}/usr/man/man1 ; ln -sf mailx.1.gz mail.1.gz )

# Add the documentation:
mkdir -p ${PKG}/usr/doc/mailx-${V}
cp -a \
 AUTHORS COPYING ChangeLog LIBS README TODO \
 ${PKG}/usr/doc/mailx-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/mailx-${V}-${ARCH}-${B}.tlz

