#!/bin/bash
#  Copyright (C) 2010  Matías A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=0.17
ARCH=${ARCH:-x86_64}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-fPIC}

PKG=${TMP}/package-bsd-finger

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/bsd-finger-${V}
lzip -cd ${CWD}/bsd-finger-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/bsd-finger-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

zcat ${CWD}/bsd-finger-0.17.patch.gz | patch -p1 --verbose

CFLAGS="$DCFLAGS" \
./configure --prefix=/usr
mkdir -p ${PKG}/usr/{sbin,bin} ${PKG}/usr/man/man{1,8}
make
make install INSTALLROOT=$PKG

# Increments a little the security:
chmod -v 0750 ${PKG}/usr/sbin/in.fingerd

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

# Compress and link manpages:
( cd ${PKG}/usr/man
  find . -type f -exec gzip -9N '{}' +
  find . -type l | while read file ; do
    ln -sf $(readlink $file).gz ${file}.gz
    rm $file
  done
)

# Add the documentation:
mkdir -p ${PKG}/usr/doc/bsd-finger-${V}
cp -a \
 BUGS ChangeLog README ${CWD}/bsd-finger.lsm \
 ${PKG}/usr/doc/bsd-finger-${V}
head -n 35 finger/finger.c | tr -d '^[*/]' \
 > ${PKG}/usr/doc/bsd-finger-${V}/LICENSE.finger
head -n 32 fingerd/fingerd.c | tr -d '^[*/]' \
 > ${PKG}/usr/doc/bsd-finger-${V}/LICENSE.fingerd

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/bsd-finger-${V}-${ARCH}-${B}.tlz

