#!/bin/bash
#  Copyright (C) 2010-2012  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=3.2.3
ARCH=${ARCH:-i486}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -march=i486 -mtune=i686}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j2}

PKG=${TMP}/package-mdadm

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/mdadm-${V}
tar xvf ${CWD}/mdadm-${V}.tar.lz -C $TMP

cd ${TMP}/mdadm-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

make $JOBS CXFLAGS="$DCFLAGS"
make install MANDIR=/usr/man DESTDIR=$PKG
chmod 750 ${PKG}/sbin/mdadm
strip --strip-unneeded ${PKG}/sbin/mdadm

mkdir -p ${PKG}/etc/sv/mdadm
cat mdadm.conf-example > ${PKG}/etc/mdadm.conf.new

install -m 755 ${CWD}/config/mdadm ${PKG}/etc/sv/mdadm/run.new
( mkdir -p ${PKG}/etc/runit/runsvdir/default
  cd ${PKG}/etc/runit/runsvdir/default
  ln -sf /etc/sv/mdadm .
)

gzip -9N ${PKG}/usr/man/man?/*
# Add the documentation:
mkdir -p ${PKG}/usr/doc/mdadm-${V}
cp -a \
 COPYING ANNOUNCE-${V} ChangeLog TODO mdadm.conf-example \
 ${PKG}/usr/doc/mdadm-${V}

# Copy the description files:
mkdir -p ${PKG}/{description,install}
cp ${CWD}/description/* ${PKG}/description

# Add post-install script:
zcat ${CWD}/post-install.gz > ${PKG}/install/post-install

cd $PKG
makepkg -l ${OUT}/mdadm-${V}-${ARCH}-${B}.tlz

