#!/bin/bash
#  Copyright (C) 2010-2011  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=8.5.11
SHORT_VER=8.5
ARCH=${ARCH:-x86_64}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-mtune=generic}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j4}

PKG=${TMP}/package-tk

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/tk${V}
lzip -cd ${CWD}/tk${V}-src.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/tk${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

export CFLAGS="$DCFLAGS"

cd unix

./configure \
 --prefix=/usr \
 --libdir=/usr/lib64 \
 --enable-shared \
 --enable-threads \
 --enable-man-symlinks \
 --enable-man-compression='gzip' \
 --enable-64bit \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS TK_LIBRARY=/usr/lib64/tk${SHORT_VER}

# The Tk package expects that its source tree is
# preserved so that packages depending on it for
# their compilation can utilize it.  This sed
# removes the references to the build directory and
# replaces them with saner system-wide locations:
sed -i \
 -e "s@^\(TK_SRC_DIR='\).*@\1/usr/include'@" \
 -e "/TK_B/s@='\(-L\)\?.*unix@='\1/usr/lib64@" \
 -e "/SEARCH/s/=.*/=''/" \
  tkConfig.sh

make install DESTDIR=$PKG TK_LIBRARY=/usr/lib64/tk${SHORT_VER}
make install-private-headers INSTALL_ROOT=$PKG

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)
strip --strip-debug ${PKG}/usr/lib64/libtkstub${SHORT_VER}.a

# Symlink compatibility:
( cd ${PKG}/usr/bin
  ln -sf wish${SHORT_VER} wish
)
( cd ${PKG}/usr/lib64
  ln -sf libtk${SHORT_VER}.so libtk.so
  ln -sf libtkstub${SHORT_VER}.a libtkstub.a
)

cd ..

# Add the documentation:
mkdir -p ${PKG}/usr/doc/tk-${V}
cp -a \
 ChangeLog README changes license.terms \
 ${PKG}/usr/doc/tk-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/tk-${V}-${ARCH}-${B}.tlz

