#!/bin/bash
#  Copyright (C) 2009-2012  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=2.11
ARCH=${ARCH:-i486}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -march=i486 -mtune=i686}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j4}

PKG=${TMP}/package-grep

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/grep-${V}
lzip -cd ${CWD}/grep-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/grep-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

CFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --bindir=/bin \
 --infodir=/usr/info \
 --mandir=/usr/man \
 --without-included-regex \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS
if [[ -n $CHECK ]]; then
  make check || true;
fi
make install DESTDIR=$PKG

# Strip binaries (egrep, fgrep, grep):
find ${PKG}/bin -type f -exec strip --strip-unneeded '{}' +

# Compress GNU info documents:
( cd ${PKG}/usr/info
  rm -f dir # Redundancy
  gzip -9N grep.info
)

# Compress man-pages and make some soft-links:
gzip -9 ${PKG}/usr/man/man1/*
( cd ${PKG}/usr/man/man1
  ln -sf grep.1.gz egrep.1.gz
  ln -sf grep.1.gz fgrep.1.gz
)

# Add the documentation:
mkdir -p ${PKG}/usr/doc/grep-${V}
cp -a \
 ABOUT-NLS AUTHORS COPYING ChangeLog NEWS README* TODO THANKS \
 ${PKG}/usr/doc/grep-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/grep-${V}-${ARCH}-${B}.tlz

