#!/bin/bash
#  Copyright (C) 2010  Matías A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=2.8.18
ARCH=${ARCH:-x86_64}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -mtune=generic}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j2}

PKG=${TMP}/package-cracklib

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/cracklib-${V}
lzip -cd ${CWD}/cracklib-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/cracklib-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

mkdir -p dicts
lzip -cd ${CWD}/cracklib-words.lz > dicts/cracklib-words

CFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --sbindir=/sbin \
 --libdir=/lib64 \
 --localstatedir=/var \
 --disable-static \
 --enable-shared \
 --with-default-dict=/lib/cracklib/pw_dict \
 --without-x \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS
make install DESTDIR=$PKG

# Make dictionaries:
install -d ${PKG}/lib/cracklib
sh util/cracklib-format dicts/cracklib* | \
 util/cracklib-packer ${PKG}/lib/cracklib/pw_dict

find ${PKG}/sbin -type f -exec chmod -v 0750 '{}' +

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

# Add the documentation:
mkdir -p ${PKG}/usr/doc/cracklib-${V}
cp -a \
 COPYING* AUTHORS ABOUT-NLS ChangeLog NEWS README* \
 ${PKG}/usr/doc/cracklib-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/cracklib-${V}-${ARCH}-${B}.tlz

