#!/bin/bash
#  Copyright (C) 2010-2012  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=4.0.1
ARCH=${ARCH:-x86_64}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -mtune=generic}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j4}

PKG=${TMP}/package-gawk

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/gawk-${V}
lzip -cd ${CWD}/gawk-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/gawk-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

CFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --libexecdir=/usr/lib64 \
 --infodir=/usr/info \
 --mandir=/usr/man \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS
if [[ -n $CHECK ]]; then
  make check;
fi
make install DESTDIR=$PKG

# Replace hard links:
( cd ${PKG}/usr/bin
  mv gawk gawk-${V}
  ln -sf gawk-${V} gawk
  mv pgawk pgawk-${V}
  ln -sf pgawk-${V} pgawk
)  

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

# Compress manuals (.info documents and man-pages):
( cd ${PKG}/usr ; rm -f info/dir ; gzip -9Nf info/* man/man?/* )

# Make some links:
( cd ${PKG}/usr/man/man1
  ln -sf gawk.1.gz awk.1.gz
  ln -sf gawk.1.gz pgawk.1.gz
)

# Add the documentation:
mkdir -p ${PKG}/usr/doc/gawk-${V}
cp -a \
 ABOUT-NLS AUTHORS COPYING ChangeLog FUTURES \
 LIMITATIONS NEWS POSIX.STD PROBLEMS README \
 ${PKG}/usr/doc/gawk-${V}
chmod 644 ${PKG}/usr/doc/gawk-${V}/*

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/gawk-${V}-${ARCH}-${B}.tlz

