#!/bin/bash
#  Copyright (C) 2010-2012  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=5.2.3
ARCH=${ARCH:-x86_64}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -mtune=generic}

PKG=${TMP}/package-lua

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/lua-${V}
lzip -cd ${CWD}/lua-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/lua-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

make PLAT=linux CFLAGS="$DCFLAGS"
mkdir -p ${PKG}/usr
make install \
 INSTALL_DATA="cp -a" \
 INSTALL_TOP=${PKG}/usr \
 INSTALL_LIB=${PKG}/usr/lib64 \
 INSTALL_CMOD=${PKG}/usr/lib64/${V:0:3}

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)
strip --strip-debug ${PKG}/usr/lib64/liblua.a

# Write the .pc file for pkgconfig:
mkdir -p ${PKG}/usr/lib64/pkgconfig
cat << EOF > ${PKG}/usr/lib64/pkgconfig/lua.pc
prefix=/usr
exec_prefix=\${prefix}
libdir=\${exec_prefix}/lib64
includedir=\${prefix}/include

Name: Lua
Description: An Extensible Extension Language
Version: ${V}
Requires: 
Libs: -L\${libdir} -llua -lm
Cflags: -I\${includedir}

EOF

# Compress manpages:
gzip -9N ${PKG}/usr/man/man?/*.?

# Add the documentation:
mkdir -p ${PKG}/usr/doc/lua-${V}/html
cp -a \
 README \
 ${PKG}/usr/doc/lua-${V}
cp -a \
 doc/*.{gif,png,html,css} \
 ${PKG}/usr/doc/lua-${V}/html

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/lua-${V}-${ARCH}-${B}.tlz

