#!/bin/bash
#  Copyright (C) 2010, 2012  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=3.10
ARCH=${ARCH:-x86_64}
B=2

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -mtune=generic}

PKG=${TMP}/package-rp-pppoe

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/rp-pppoe-${V}
tar xvf ${CWD}/rp-pppoe-${V}.tar.lz -C $TMP

cd ${TMP}/rp-pppoe-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

# Change the docdir location:
sed -i 's|/share/doc|/doc|' src/Makefile.in

# Adjust the path of ifconfig(1):
( cd scripts && zcat ${CWD}/ifconfig-path.diff.gz | patch -p0 --verbose )

cd src
autoconf

CFLAGS="$DCFLAGS" \
./configure \
 --sysconfdir=/etc \
 --mandir=/usr/man \
 --docdir=/usr/doc/rp-pppoe-${V} \
 --disable-debugging \
 --build=${ARCH}-dragora-linux-gnu

make
make install DESTDIR=$PKG

# Check under /usr/lib{,64}/pppd/{version}/rp-pppoe.so:
rm -rf ${PKG}/etc/ppp/plugins

# Increments a little the security:
find ${PKG}/usr/sbin -type f | xargs chmod 750

# Handle config files:
mkdir -p ${PKG}/etc/ppp
cd ${PKG}/etc/ppp
for file in firewall-standalone pppoe.conf \
 pppoe-server-options firewall-masq
do
  mv $file{,.new}
done

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

# Compress man-pages:
gzip -9N ${PKG}/usr/man/man{5,8}/*.?

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

# Add the post-install script:
mkdir -p ${PKG}/install
zcat ${CWD}/post-install.gz > ${PKG}/install/post-install

cd $PKG
makepkg -l ${OUT}/rp-pppoe-${V}-${ARCH}-${B}.tlz

