#!/bin/bash
#  Copyright (C) 2012  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

P=acpid
V=${V:-2.0.14}
ARCH=${ARCH:-x86_64}
B=${B:-1}

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -mtune=generic}

PKG=${TMP}/package-${P}

rm -rf $PKG
mkdir -p $PKG $OUT

rm -rf ${TMP}/${P}-${V}
echo "Uncompressing the tarball..."
tar -xvf ${CWD}/${P}-${V}.tar.lz -C $TMP

cd ${TMP}/${P}-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \
 \) -exec chmod 755 {} + \
 -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \
 \) -exec chmod 644 {} +

make install OPT="$DCFLAGS" \
     PREFIX=/usr \
     MANDIR=/usr/man \
     DOCDIR=/usr/doc/acpid-${V} \
     DESTDIR=$PKG

# Increment the security:
chmod -v 0750 ${PKG}/usr/sbin/acpid

# Add the init script for runit:
install -m 0755 ${CWD}/runit/acpid -D ${PKG}/etc/sv/acpid/run.new
mkdir -p ${PKG}/etc/runit/runsvdir/default
( cd ${PKG}/etc/runit/runsvdir/default ; ln -sf /etc/sv/acpid . )

# Install configuration files:
install -m 0644 ${CWD}/files/defconfig -D ${PKG}/etc/acpi/events/defconfig
install -m 0755 ${CWD}/files/acpi_handler -D ${PKG}/etc/acpi/acpi_handler.new

cd $PKG

# Strip binaries & libraries:
find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
 cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true;

# Copy the description files with the post-install script:
mkdir -p description install
cp ${CWD}/description/?? description/
zcat ${CWD}/post-install.gz > install/post-install

# Build the package:
makepkg -l ${OUT}/${P}-${V}-${ARCH}-${B}.tlz

