#!/bin/bash
#  Copyright (C) 2011-2012  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

P=icedtea-web
V=${V:-1.1.7}
ARCH=${ARCH:-i486}
case "$ARCH" in
  i*) PKG_ARCH=i586;;
esac
B=${B:-1}

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -mtune=generic}

PKG=${TMP}/package-${P}

rm -rf $PKG
mkdir -p $PKG $OUT

rm -rf ${TMP}/${P}-${V}
echo "Uncompressing the tarball..."
tar -xvf ${CWD}/${P}-${V}.tar.lz -C $TMP

cd ${TMP}/${P}-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \
 \) -exec chmod 755 {} + \
 -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \
 \) -exec chmod 644 {} +

CFLAGS="$DCFLAGS" \
CXXFLAGS="$DCFLAGS" \
./configure \
 --prefix=/opt/icedtea6/jre \
 --mandir=/usr/man \
 --with-jdk-home=/opt/jdk \
 --with-ecj-jar=/usr/share/java/ecj.jar \
 --disable-docs \
 --build=${ARCH}-dragora-linux-gnu

make
make install DESTDIR=$PKG

# Move man pages to the right location:
if [[ -d ${PKG}/opt/icedtea6/jre/man ]]; then
  mkdir -p ${PKG}/usr
  mv ${PKG}/opt/icedtea6/jre/man/ ${PKG}/usr
fi

# Make symlinks in /usr/bin:
mkdir -p ${PKG}/usr/bin
for file in itweb-settings javaws ; do
  ( cd ${PKG}/usr/bin
    ln -s /opt/icedtea6/jre/bin/${file} .
  )
done

# Make symlink compatibility with browser plugin:
mkdir -p ${PKG}/usr/lib/plugins/mozilla
( cd ${PKG}/usr/lib/plugins/mozilla
  ln -sf /opt/icedtea6/jre/lib/IcedTeaPlugin.so .
)

# Install .desktop files:
mkdir -p ${PKG}/usr/share/{applications,pixmaps}
install -m 644 *.desktop ${PKG}/usr/share/applications
install -m 644 javaws.png ${PKG}/usr/share/pixmaps

# Compress and link .man page(s)?:
if [[ -d ${PKG}/usr/man ]]; then
  ( cd ${PKG}/usr/man
    find . -type f -exec gzip -9N '{}' +
    find . -type l | while read file ; do
      ln -sf $(readlink $file).gz ${file}.gz
      rm $file
    done
  )
fi

# Copy the documentation:
mkdir -p ${PKG}/usr/doc/${P}-${V}
cp -a \
 AUTHORS COPYING ChangeLog NEWS \
 ${PKG}/usr/doc/${P}-${V}

cd $PKG

# Strip binaries & libraries:
find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
 cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true;

# Copy the description files:
mkdir -p description install
cp ${CWD}/description/?? description/
zcat ${CWD}/post-install.gz > install/post-install

# Build the package:
makepkg -l ${OUT}/${P}-${V}-${PKG_ARCH}-${B}.tlz

