#!/bin/bash
#  Copyright (C) 2010-2011  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=3.0
ARCH=${ARCH:-i486}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -march=i486 -mtune=i686}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j5}

PKG=${TMP}/package-parted

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/parted-${V}
lzip -cd ${CWD}/parted-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/parted-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

CFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --infodir=/usr/info \
 --mandir=/usr/man \
 --disable-debug \
 --disable-static \
 --enable-shared \
 --disable-pc98 \
 --disable-dynamic-loading \
 --enable-device-mapper \
 --with-readline \
 --with-packager="Matias A. Fonzo, <selk@dragora.org>" \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS V=1 || make;
make install DESTDIR=$PKG

find ${PKG}/usr/sbin -type f -exec chmod -v 750 '{}' +

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

# Compress manual(s):
( cd ${PKG}/usr/info
  rm -f dir  # Redundancy.
  gzip -9N *
)

# Compress man page(s):
gzip -9N ${PKG}/usr/man/man?/*.?

# Add the documentation:
mkdir -p ${PKG}/usr/doc/parted-${V}
cp -a \
 ABOUT-NLS AUTHORS BUGS COPYING ChangeLog NEWS README THANKS TODO \
 ${PKG}/usr/doc/parted-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/?? ${PKG}/description

cd $PKG
makepkg -l ${OUT}/parted-${V}-${ARCH}-${B}.tlz

