#!/bin/bash
#  Copyright (C) 2010, 2012  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=1.3.3
ARCH=${ARCH:-x86_64}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -mtune=generic}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j4}

PKG=${TMP}/package-libvorbis

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/libvorbis-${V}
lzip -cd ${CWD}/libvorbis-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/libvorbis-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

# Fix the documentation directory:
for file in \
 fixup.docdir fixup.htmldir-vorbisenc fixup.htmldir-vorbisfile
do
  zcat ${CWD}/${file}.diff.gz | patch -p0 --verbose
done

CFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --libdir=/usr/lib64 \
 --mandir=/usr/man \
 --docdir=/usr/doc/libvorbis-${V} \
 --htmldir=/usr/doc/libvorbis-${V}/html \
 --localstatedir=/var \
 --disable-static \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS
make install DESTDIR=$PKG

# Nope:
rm -rf ${PKG}/usr/share/doc

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

# Compress manpages (if needed):
if [[ -d ${PKG}/usr/man ]]; then
  ( cd ${PKG}/usr/man
    gzip -9N man?/*.?
  )
fi

# Save the timestamp of the documentation:
mkdir -p ${PKG}/usr/doc/libvorbis-${V}
cp -a \
 AUTHORS CHANGES COPYING README \
 ${PKG}/usr/doc/libvorbis-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/libvorbis-${V}-${ARCH}-${B}.tlz

