#!/bin/bash
#  Copyright (C) 2010-2012  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=3.0.1
ARCH=${ARCH:-x86_64}
B=3

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -mtune=generic}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j4}

PKG=${TMP}/package-mpfr

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/mpfr-${V}
lzip -cd ${CWD}/mpfr-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/mpfr-${V}

# Apply official patches:
if [[ -f ${CWD}/patches/allpatches ]]; then
  patch --verbose -N -Z -p1 < ${CWD}/patches/allpatches
fi

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

CFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --libdir=/usr/lib64 \
 --localstatedir=/var \
 --infodir=/usr/info \
 --docdir=/usr/doc/mpfr-${V} \
 --htmldir=/usr/doc/mpfr-${V}/html \
 --enable-thread-safe \
 --with-gmp=/usr \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS
if [[ -n $CHECK ]]; then
  make check;
fi
make install DESTDIR=$PKG

# Make symlink compatibility:
( cd ${PKG}/usr/lib64
  ln -sf libmpfr.so.4.0.1 libmpfr.so.1
)

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
  find . -type f | xargs file | awk '/current ar archive/' | \
   cut -f 1 -d : | xargs strip --strip-debug 2> /dev/null
)

# Compress GNU info documents:
( cd ${PKG}/usr/info ; rm -f dir ; gzip -9N * )

# Add the documentation:
mkdir -p ${PKG}/usr/doc/mpfr-${V}
cp -a \
 AUTHORS BUGS COPYING* ChangeLog NEWS \
 PATCHES README TODO VERSION FAQ.html \
 ${PKG}/usr/doc/mpfr-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/mpfr-${V}-${ARCH}-${B}.tlz

