#!/bin/bash
#  Copyright (C) 2010-2011  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=1.3.7
ARCH=${ARCH:-i486}
B=2

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-Os}

PKG=${TMP}/package-icewm

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/icewm-${V}
lzip -cd ${CWD}/icewm-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/icewm-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

# Apply patches from IceWM Sourceforge:
zcat ${CWD}/patches/0001-Add-new-option-TaskBarClockUpdateInterval-for-reduci.patch.gz | \
 patch -p1 --verbose

CFLAGS="$DCFLAGS" \
CXXFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --localstatedir=/var \
 --mandir=/usr/man \
 --enable-corefonts \
 --disable-x86-asm \
 --with-docdir=/usr/doc/icewm-${V} \
 --with-mkfontdir=/usr/bin/mkfontdir \
 --with-x \
 --build=${ARCH}-dragora-linux-gnu

make
make install install-desktop DESTDIR=$PKG

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

# Add the xinitrc entry for icewm:
mkdir -p ${PKG}/etc/X11/xinit
zcat ${CWD}/xinitrc-32.gz > ${PKG}/etc/X11/xinit/xinitrc.icewm
chmod 755 ${PKG}/etc/X11/xinit/xinitrc.icewm
(
  cd ${PKG}/etc/X11/xinit
  ln -sf xinitrc.icewm xinitrc
)

# Compress manpages (if needed):
if [[ -d ${PKG}/usr/man ]]; then
  for manpage in ${PKG}/usr/man/man?/*.? ; do
    gzip -9N $manpage
  done
fi

# Add the documentation:
mkdir -p ${PKG}/usr/doc/icewm-${V}
cp -a \
 AUTHORS BUGS CHANGES COPYING PLATFORMS README* TODO VERSION icewm.lsm \
 ${PKG}/usr/doc/icewm-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/icewm-${V}-${ARCH}-${B}.tlz

