#!/bin/sh
#
# sshd:  OpenSSH daemon.
#

if [ -x /usr/sbin/sshd ]; then
  # Generate host keys (if needed):
  if [ -x /usr/bin/ssh-keygen ]; then
    if [ ! -f /etc/ssh/ssh_host_key ]; then
      /usr/bin/ssh-keygen -t rsa1 -f /etc/ssh/ssh_host_key -N ''
    fi
    if [ ! -f /etc/ssh/ssh_host_rsa_key ]; then
      /usr/bin/ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N ''
    fi
    if [ ! -f /etc/ssh/ssh_host_dsa_key ]; then
      /usr/bin/ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key -N ''
    fi
  fi
  exec /usr/sbin/sshd -D
fi

