#!/bin/bash
#  Copyright (C) 2010-2011  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=2.2.51
ARCH=${ARCH:-x86_64}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -mtune=generic}

PKG=${TMP}/package-acl

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/acl-${V}
lzip -cd ${CWD}/acl-${V}.src.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/acl-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

# Change the locations of the paths:
zcat ${CWD}/builddefs.diff.gz | patch -p0 --verbose

export CFLAGS="$DCFLAGS"

./configure \
 --prefix=/usr \
 --libdir=/usr/lib64 \
 --libexecdir=/usr/lib64 \
 --mandir=/usr/man \
 --docdir=/usr/doc \
 --build=${ARCH}-dragora-linux-gnu

make
make DESTDIR=$PKG install install-lib install-dev

# Remove bogus files:
rm -f ${PKG}/usr/lib64/*.{a,la}

# Insert the real library:
cat libacl/.libs/libacl.a > ${PKG}/usr/lib64/libacl.a

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)
strip --strip-debug ${PKG}/usr/lib64/libacl.a

# Move shared libs to ${PKG}/lib64:
( cd $PKG
  mkdir -p lib64
  mv  usr/lib64/libacl.so* lib64/
  ( cd usr/lib64 ; ln -sf ../../lib64/libacl.so.1.1.0 libacl.so )
  # Fix perm:
  chmod 755 lib64/libacl.so.1.1.0
)

# Compress and link manpages:
#( cd ${PKG}/usr/man
#  find . -type f -exec gzip -9N '{}' +
#  find . -type l | while read file ; do
#    ln -sf $(readlink $file).gz ${file}.gz
#    rm $file
#  done
#)

# No usr/share/doc directory, the files does not
# contains the same timestamp:
rm -rf ${PKG}/usr/share/doc

# Add the documentation:
mkdir -p ${PKG}/usr/doc/acl-${V}
cp -a \
 doc/{CHANGES,COPYING,PORTING,TODO} README \
 ${PKG}/usr/doc/acl-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/acl-${V}-${ARCH}-${B}.tlz

