#!/bin/bash
#  Copyright (C) 2010-2012  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=1.8.4p2
ARCH=${ARCH:-i486}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -march=i486 -mtune=i686}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j4}

PKG=${TMP}/package-sudo

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/sudo-${V}
lzip -cd ${CWD}/sudo-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/sudo-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

CFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --sysconfdir=/etc \
 --mandir=/usr/man \
 --docdir=/usr/doc/sudo-${V} \
 --localstatedir=/var \
 --disable-static \
 --enable-noargs-shell \
 --disable-root-sudo \
 --with-logfac=auth \
 --with-ignore-dot \
 --with-sendmail \
 --without-pam \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS
make install DESTDIR=$PKG

# Changes the permission of "sudo/visudo":
chmod -v 4711 ${PKG}/usr/bin/sudo
chmod -v 750  ${PKG}/usr/sbin/visudo
# Changes the hardlink to softlink:
( cd ${PKG}/usr/bin ; ln -sf sudo sudoedit )

# To handle config:
mv ${PKG}/etc/sudoers{,.new}

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

# Compress manpages:
( cd ${PKG}/usr/man
  find . -type f -perm 444 | xargs chmod 644  # Fix permissions.
  gzip -9N --force man?/*
  cd man8
  ln -sf sudo.8.gz sudoedit.8.gz
)

# Add the documentation:
mkdir -p ${PKG}/usr/doc/sudo-${V}
cp -a \
 ChangeLog doc/{HISTORY,LICENSE,TROUBLESHOOTING,UPGRADE,sample.*} \
 NEWS README* \
 ${PKG}/usr/doc/sudo-${V}

# Add the post-install script:
mkdir -p ${PKG}/install
zcat < ${CWD}/post-install.gz > ${PKG}/install/post-install

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/sudo-${V}-${ARCH}-${B}.tlz

