#!/bin/bash
#  Copyright (C) 2010, 2012  Matias A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=1.11.23
ARCH=${ARCH:-i486}
B=2

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j4}

PKG=${TMP}/package-cvs

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/cvs-${V}
lzip -cd ${CWD}/cvs-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/cvs-${V}

# A patch to use the external zlib instead of
# the copy included on cvs (thanks to BLFS):
zcat ${CWD}/patches/cvs-1.11.23-zlib-1.patch.gz | patch -p1 --verbose

# http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2010-3846
( cd src && \
  zcat ${CWD}/patches/CVE-2010-3846.patch.gz | \
   patch -p0 --verbose
)

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

autoreconf

CFLAGS="$DCFLAGS" \
./configure \
 --prefix=/usr \
 --infodir=/usr/info \
 --mandir=/usr/man \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS
make install DESTDIR=$PKG

( cd ${PKG}/usr/bin && ln -sf /usr/share/cvs/contrib/rcs2log . )

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

# Add the profile:
install -m 0755 ${CWD}/profile.d/cvs -D ${PKG}/etc/profile.d/cvs.new

# Add the cvs file for xinetd:
mkdir -p ${PKG}/etc/xinetd.d
zcat ${CWD}/cvs.xinetd.gz > ${PKG}/etc/xinetd.d/cvs

# Compress pages:
( cd ${PKG}/usr
  rm -f info/dir  # Redundancy.
  gzip -9N info/* man/man?/*.?
)

# Add the documentation:
mkdir -p ${PKG}/usr/doc/cvs-${V}
cp -a \
 AUTHORS BUGS COPYING* ChangeLog* DEVEL-CVS FAQ HACKING \
 MINOR-BUGS NEWS PROJECTS README* TESTS TODO \
 ${PKG}/usr/doc/cvs-${V}
(
  cd ${PKG}/usr/doc/cvs-${V}
  ln -sf /usr/share/cvs/contrib .
)

# Add the post-install script:
mkdir -p ${PKG}/install
zcat ${CWD}/post-install.gz > ${PKG}/install/post-install

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/cvs-${V}-${ARCH}-${B}.tlz

