#!/bin/bash
#  Copyright (C) 2010  Matías A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=1.0
ARCH=${ARCH:-x86_64}
B=1

# Flags for the compiler:
DCFLAGS=${DCFLAGS:=-O2 -fPIC}

# Parallel jobs for the compiler:
JOBS=${JOBS:=-j4}

PKG=${TMP}/package-adcd

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/adcd-${V}
lzip -cd ${CWD}/adcd-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/adcd-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

./configure \
 --prefix=/usr \
 --mandir=/usr/man \
 --build=${ARCH}-dragora-linux-gnu

make $JOBS CXXFLAGS="$DCFLAGS"
make install DESTDIR=$PKG

strip --strip-unneeded ${PKG}/usr/bin/adcd
gzip -9N ${PKG}/usr/man/man1/adcd.1

# Add the documentation:
mkdir -p ${PKG}/usr/doc/adcd-${V}
cp -a \
 AUTHORS COPYING ChangeLog LEEME NEWS README \
 ${PKG}/usr/doc/adcd-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/adcd-${V}-${ARCH}-${B}.tlz

