#!/bin/bash
#  Copyright (C) 2010  Matías A. Fonzo, <selk@dragora.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

CWD=$(pwd)

TMP=${TMP:-/tmp/sources}
OUT=${OUT:-/tmp/packages}

V=1.60
ARCH=${ARCH:-i486}
B=1

PKG=${TMP}/package-net-tools

rm -rf $PKG
mkdir -p $PKG $OUT

echo "Uncompressing the tarball..."
rm -rf ${TMP}/net-tools-${V}
lzip -cd ${CWD}/net-tools-${V}.tar.lz | tar -xvf - -C $TMP

cd ${TMP}/net-tools-${V}

# Set sane ownerships and permissions:
chown -R 0:0 .
find . \
 \( -perm 2777 -o \
    -perm 777  -o \
    -perm 775  -o \
    -perm 711  -o \
    -perm 555  -o \
    -perm 511     \
 \) -exec chmod 755 {} + \
  -o \
 \( -perm 666 -o \
    -perm 664 -o \
    -perm 600 -o \
    -perm 444 -o \
    -perm 440 -o \
    -perm 400    \
 \) -exec chmod 644 {} +

# Apply patches from Debian:
zcat ${CWD}/patches/net-tools_1.60-22.diff.gz | patch -p1 --verbose

# Change the location of the manpages:
sed -i 's#mandir=/usr/share/man#mandir=/usr/man#g' man/Makefile

yes | make
make install BASEDIR=$PKG

# Increments a little the security:
find ${PKG}/sbin -type f | xargs chmod 750 -v

# The replacement for "ifconfig/route" is iproute2, so:
for file in ifconfig route ; do
 find $PKG -type f -name "$file*" -delete
done

# Do not override this manpage:
find $PKG -type f -name 'hostname.1*' -delete

# Strip binaries & libraries:
( cd $PKG
  find . -type f | xargs file | awk '/ELF/ && /executable/ || /shared object/' | \
   cut -f 1 -d : | xargs strip -s 2> /dev/null
)

# Compress and link manpages (if any):
( cd ${PKG}/usr/man
  find . -type f -exec gzip -9N '{}' +
  find . -type l | while read file ; do
    ln -sf $(readlink $file).gz ${file}.gz
    rm $file
  done
)

# Add the documentation:
mkdir -p ${PKG}/usr/doc/net-tools-${V}
cp -a \
 ABOUT-NLS COPYING README* TODO \
 ${PKG}/usr/doc/net-tools-${V}

# Copy the description files:
mkdir -p ${PKG}/description
cp ${CWD}/description/* ${PKG}/description

cd $PKG
makepkg -l ${OUT}/net-tools-${V}-${ARCH}-${B}.tlz

